### ISSUE TITLE
Supply multiple module configurations in one file

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#101]
It would be nice to allow for supplying multiple module configurations per file.  This would allow for supplying the configuration for deploying combinations of vdm's and storage platforms that can be started using existing methods.

**Comment by clintonskitson** [comment]
@akutz based on our previous conversation I believe this is the proper thread to capture the investigation of pulling this feature backwards to 0.3.2.

The request is that we want to be able to have multiple modules running that each have their own unique `unix socket` and set of drivers configured.  There can be a couple of use cases here.

1) If someone has multiple ScaleIO instances running, a single host or RR instance should be able to target each ScaleIO instance through modules.  Each module would have a unique unix socket, api endpoint, and creds etc.
2) A single storage platform should be able to be configured multiple times but with different default behaviors.  For example, there are default behaviors for the Docker Volume driver for size of volume created.  The feature should enable the same platform, but with different default behaviors configured.

**Comment by clintonskitson** [comment]
The alternative to bringing the whole feature back would be to implement the ability to specify unix socket when starting a module.

`./rexray service module instance start --id=3 --config=/etc/rexray/config2.yml --socket=uni
x:///var/run/rexray2.sock`

**Comment by akutz** [comment]
Hi @clintonskitson,

How important is it to retain the ability to configure the service via the command line for now?

**Comment by clintonskitson** [comment]
Not important.  But later on I could see the need to stop and start modules
dynamically without doing a rexray restart.

**Comment by akutz** [comment]
Hi @clintonskitson,

That's service control, not configuration. That would not be lost. what's the ETA on this deliverable?

**Comment by akutz** [comment]
Hi @clintonskitson,

Unless by "start/stop" you mean "start new configurations?"

**Comment by clintonskitson** [comment]
The target is RC2.  Yes service control is not a top priority right now as
it does not work since you cannot specify different UNIX sockets anyhow.

**Comment by akutz** [comment]
Hi @clintonskitson,

RC2 yes, but RC2 is needed yesterday? Tomorrow? 2087? :) I know this is being driven by a customer ask, so I'm asking what's the priority in terms of a desired deliverable date?

**Comment by akutz** [comment]
Closed with #275
