### ISSUE TITLE
VirtualBox storage driver?

### ISSUE THREAD

**Issue by md5** [emccode/rexray#104]
Would it make sense to have a VirtualBox storage driver for REX-Ray?

I started working on a VirtualBox volume driver plugin over at [`appropriate/docker-volumes-virtualbox`](https://github.com/appropriate/docker-volumes-virtualbox) that uses the `vboxwebsrv` SOAP service, but I had to put it on the backburner before getting to the point of having the VM format and mount the volume. Part of this was due to the tediousness of the `vboxwebsrv` SOAP interface and part of it was simply due to lack of time.

Since REX-Ray is already handling the formatting and mounting part as far as I understand it, I was wondering if it would make more sense for me to repurpose my code to be a REX-Ray storage driver and thereby avoid having to do some of that extra work.

Do REX-Ray storage drivers need to be integrated with this project, or is there a way to build them as a separate binary that lives in its own project?

**Comment by clintonskitson** [comment]
Wow that's a great idea @md5, nice job getting that going.  Yup, exposing the capabilities that you have already done around instance discovery is a great first step for a RR driver.

Yup by repurposing you get to take advantage of the RR framework including the mounting and formatting aspect.

We would gladly accept a PR with a VB volume driver here.  I'm not quote sure if I totally follow your question though.  If the question is whether you could build another CLI that implements RR as a package, the answer is yes.  This would allow you to implement your own CLI and take advantage of RR capabilities.

**Comment by md5** [comment]
My question was whether the right approach would be to add a `storage/virtualbox` directory with a storage driver implementation to this project or whether it would make more sense for it to be maintained as a separate project somehow (similar to how Docker volume drivers are separate from the Docker daemon).

**Comment by clintonskitson** [comment]
Ok, the right approach would be to create a `storage/virtualbox` directory.

**Comment by md5** [comment]
Sounds good. It looks like all the necessary functionality could be encapsulated behind that interface. I was wondering whether stuff like discovering the instance identity was in a separate interface, but it appears from the EC2 example that it isn't.

BTW, you guys have a typo in the `ec2` driver. It says `getInstanceIdendityDocument` instead of `getInstanceIdentityDocument`.

**Comment by clintonskitson** [comment]
Closing this since it has been merged https://github.com/emccode/rexray/pull/209

**Comment by clintonskitson** [comment]
Btw.. this driver is built for VirtualBox v4 currently.  We ran into issues with v5.0.10 https://www.virtualbox.org/search?ticket=on&changeset=on&wiki=on&q=locktype&page=2&noquickjump=1
