### ISSUE TITLE
rename "remove" to "delete"

### ISSUE THREAD

**Issue by kacole2** [emccode/rexray#106]
again, just another suggestion.

`remove` sounds like "i'm going to remove this from my inventory" or "remove this from this machine". Perhaps `delete` makes it feel like "are you sure you want to do this?"

**Comment by clintonskitson** [comment]
I'm not sure about this one.  We are following a standard Linux command here, `rm`.

**Comment by kacole2** [comment]
makes sense... perhaps we should shorthand it to `rm`

**Comment by clintonskitson** [comment]
agreed on that

**Comment by akutz** [comment]
I will add `rm` as an alias.

**Comment by akutz** [comment]
Please note that the `snapshot remove` command was already aliased, so would too `volume remove` had there not been a bug and I aliased that to `create` instead.
