### ISSUE TITLE
Installing REX-Ray on CoreOS fails with command not found

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#108]
Running the `sh` install method is erroring out.  It looks like because `lsb-release` exists, it is trying to do an apt package install.  I am not very savvy with why the `lsb-release` would be something tagged to determine a valid apt install.

```
core@ip-10-0-1-223 ~ $ curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -
sudo: dpkg: command not found

REX-Ray has been installed to /usr/bin/rexray

sh: line 45: /usr/bin/rexray: No such file or directory
```

```
elif [ "$ARCH" = "x86_64" -a \
       -e "/etc/debian-release" -o \
       -e "/etc/debian-version" -o \
       -e "/etc/lsb-release" ]; then
```

```
core@ip-10-0-1-223 ~ $ cat /etc/lsb-release 
DISTRIB_ID=CoreOS
DISTRIB_RELEASE=723.3.0
DISTRIB_CODENAME="Red Dog"
DISTRIB_DESCRIPTION="CoreOS 723.3.0"
```

**Comment by akutz** [comment]
Hi @clintonskitson,

Did you read the script? It notes how distributions are determined. 

![image](https://cloud.githubusercontent.com/assets/101085/10239698/3230372a-6897-11e5-949e-862fcc2f6d32.png)

Here's [the link](http://bit.ly/1JkNwWx). It seems CoreOS decided to adopt a file used by Ubuntu but use a RPM based package manager. Pretty dumb on their part.

**Comment by akutz** [comment]
Yep, pretty much CoreOS being dumb as `lsb_release` is still an Ubuntu thing today. 

![image](https://cloud.githubusercontent.com/assets/101085/10239739/b4a91b68-6897-11e5-8c2c-ec3119be3d7b.png)

Okay, after more reading they use lsb-release but *no* package manager at all. Hey @drumulonimbus, I guess that's one good reason we don't just do packages, huh? :) Anyway, we'll need to have a special catch for CoreOS.

**Comment by clintonskitson** [comment]
Didn't read it, just throwing the info out there before researching it..

**Comment by clintonskitson** [comment]
It looks like the destination of the binary needs to go into the `/opt/rexray/bin` directory since they consider other places in the filesystem read-only.

```
core@ip-10-0-1-223 ~ $ sudo mkdir /opt/rexray/bin -p
core@ip-10-0-1-223 ~ $ mv rexray /opt/rexray/bin/.
mv: cannot move 'rexray' to '/opt/rexray/bin/./rexray': Permission denied
core@ip-10-0-1-223 ~ $ sudo mv rexray /opt/rexray/bin/.
core@ip-10-0-1-223 ~ $ sudo /opt/rexray/bin/rexray install  
REX-Ray is now installed. Before starting it please check http://github.com/emccode/rexray for instructions on how to configure it.

 Once configured the REX-Ray service can be started with the command 'sudo systemctl start rexray'.
```

**Comment by akutz** [comment]
Hi @clintonskitson,

Oh, yeah, hmmm. How's that work out for you? :)

**Comment by clintonskitson** [comment]
```
core@ip-10-0-1-223 ~ $ df /usr/bin
Filesystem     1K-blocks   Used Available Use% Mounted on
/dev/xvda3       1007760 354076    601668  38% /usr
core@ip-10-0-1-223 ~ $ df /bin
Filesystem     1K-blocks   Used Available Use% Mounted on
/dev/xvda3       1007760 354076    601668  38% /usr
```

https://coreos.com/os/docs/latest/sdk-disk-partitions.html

**Comment by akutz** [comment]
Hi @clintonskitson,

Hmm, one more good reason that I support custom install paths :)

Okay, please give me the means to detect CoreOS. Please look it up and make sure it stays very, very simple. A file detection if possible. Or the output of a single command. Try `lsb_release -a` and see what happens. 

If that's the case we'll fetch the tarball and I'll install it at a specific directory. No issue.

**Comment by akutz** [comment]
Hi @clintonskitson,

I wasn't testing CoreOS, were you? If not, who was? I guess we should add it to our test matrix. I was only actively testing CentOS and Ubuntu.

**Comment by clintonskitson** [comment]
One more thing.. we need to update the path as well.  I believe a file in `/etc/profile.d` that did something like this.. `export PATH="/opt/rexray/bin:$PATH"`

```
core@ip-10-0-1-223 ~ $ echo $PATH
/opt/mesosphere/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
```

**Comment by akutz** [comment]
Hi @clintonskitson,

Hmm, so what you're telling me is that CoreOS does not provide package managers and requires installation in `/opt`? Huh. Who could have figured that? :)

**Comment by clintonskitson** [comment]
=)

**Comment by akutz** [comment]
Hi @clintonskitson,

And yes, I'm the one that advertised the `/etc/profile.d/rexray` idea. I'll add it there. Or you can fork it and do it yourself. All you have to do is edit the `install.sh` file. Do you BASH pretty well? Or would you like to leave it up to me?

**Comment by clintonskitson** [comment]
I'm ok for now and need to focus on some other stuff.  It would be nice to get this dialed in early next week before MesosCon though, so yes please do =).  It relates to enabling Mesosphere to easily work with REX-Ray.

**Comment by akutz** [comment]
Hi @clintonskitson,

You'll have to do it unless you're going to help me get my EC2 working. I'm still having VPC issues.

![image](https://cloud.githubusercontent.com/assets/101085/10239869/ebf121d6-6899-11e5-956d-5218261c3611.png)

**Comment by clintonskitson** [comment]
Just fire up a 723.3.0 CoreOS image or something newer from the AMIs.

**Comment by akutz** [comment]
SSH into the box and execute `lsb_release -a` and give me the result. I can get 90% of the way there from that. After that we can work together on testing.

**Comment by clintonskitson** [comment]
Duh =) Actually sign up for Digital Ocean, super easy

**Comment by akutz** [comment]
That's what I did! It resulted in this.

**Comment by clintonskitson** [comment]
lsb-release is above

**Comment by akutz** [comment]
No it's not. I said execute `lsb_release -a`. You cat'd the file.

**Comment by clintonskitson** [comment]
Linking the issue from `dvdcli` here as well

**Comment by akutz** [comment]
I've got a ton of stuff myself, my AmEx is expired, and I just need a little testing. I need yours or someone else's help on this, that's just the way it is for now. So if not you, please let me know with whom to coordinate.

**Comment by clintonskitson** [comment]
No problem will send an instance over

**Comment by akutz** [comment]
Found an ISO.

**Comment by clintonskitson** [comment]
The lsb_release bin isn't available

**Comment by akutz** [comment]
Instances are useless if I can't start them. Unless you're granting me access to one of yours.

**Comment by akutz** [comment]
Ah, good to know.

**Comment by akutz** [comment]
![image](https://cloud.githubusercontent.com/assets/101085/10239944/121aac28-689b-11e5-852e-9641f8e661d2.png)

**Comment by akutz** [comment]
I'm guessing testing for the existence of the directory `/usr/share/coreos` will work.

**Comment by clintonskitson** [comment]
`grep DISTRIB_ID=CoreOS /etc/lsb-release`?

**Comment by akutz** [comment]
I could do that, but I prefer to KISS.

**Comment by clintonskitson** [comment]
I just don't know whether the `/usr/share/coreos` dir may exist or not on other distros if some of CoreOS's other wares are present.

**Comment by akutz** [comment]
You worry too much and/or you don't know me at all yet.

**Comment by akutz** [comment]
Hi @clintonskitson,

CoreOS support added with commit dd36deb248911bc72d1d0c2e8efcb945683c8455.

**Comment by drcrallen** [comment]
Looks like this broke again

```
$ cat /etc/lsb-release
DISTRIB_ID="Container Linux by CoreOS"
DISTRIB_RELEASE=1395.0.0+2017-05-08-2122
DISTRIB_CODENAME="Ladybug"
DISTRIB_DESCRIPTION="Container Linux by CoreOS 1395.0.0+2017-05-08-2122 (Ladybug)"
```

**Comment by drcrallen** [comment]
`grep DISTRIB_ID=CoreOS /etc/lsb-release` indeed did not last

**Comment by clintkitson** [comment]
Thanks for the info @drcrallen

**Comment by akutz** [comment]
Hi @clintkitson,

Didn't @codenrhoden *just* fix this for https://github.com/codedellemc/rexray/issues/793? I wonder if he updated the install script on bintray with the change. Looking now.

**Comment by akutz** [comment]
Hi @clintkitson and @drcrallen,

While @codenrhoden fixed this in the install script, the change was not uploaded to the Bintray repository. I'm doing so now....

And it's done:

```bash
$ curl -sSL https://emccode.bintray.com/rexray/install | grep 'grep CoreOS'
    grep DISTRIB_ID /etc/lsb-release 2> /dev/null | grep CoreOS 2> /dev/null
```
