### ISSUE TITLE
Retrieve instance UUID in Openstack

### ISSUE THREAD

**Issue by maricaantonacci** [emccode/rexray#111]
Using rackspace driver results in an error while getting instance uuid with /usr/bin/xenstore-read
The UUID may be retrieved using command /usr/sbin/dmidecode:
```
Handle 0x0100, DMI type 1, 27 bytes
System Information
	Manufacturer: OpenStack Foundation
	Product Name: OpenStack Nova
	Version: 2014.2.3
	Serial Number: 47513848-0036-2500-905b-0025905bca52
	UUID: 70671C29-1E7A-48BC-BBBB-24AC5CFF0DE9
	Wake-up Type: Power Switch
	SKU Number: Not Specified
	Family: Not Specified
```

**Comment by clintonskitson** [comment]
I have created a special branch to help troubleshoot this.

Download `rexray` from here.  Make sure to run it with `./rexray` for now.  
https://drive.google.com/file/d/0B6vlRdQM169ucm4xWDloVDVhVGM/view?usp=sharing

I introduced new parameters in this patchfor Openstack versus the previous Rackspace ones.  Please also indicate `openstack` as a storage driver.
```
      --openstackAuthUrl="": 
      --openstackDomainId="": 
      --openstackDomainName="": 
      --openstackPassword="": 
      --openstackTenantId="": 
      --openstackTenantName="": 
      --openstackUserId="": 
      --openstackUserName="": 
```

**Comment by maricaantonacci** [comment]
It fails. I think because of upper case. The command should be:

/usr/sbin/dmidecode | awk '/UUID:/ {print tolower($2)}' 

The error message:
DEBU[0000] error initializing driver                     driverName=Openstack error.provider=Openstack error.cmd.Args=[/usr/sbin/dmidecode | awk '/UUID:/ {print $2;}'] error.cmd.Out=[] error.cmd.Path="/usr/sbin/dmidecode | awk '/UUID:/ {print $2;}'" error.message="error getting instance id"

**Comment by clintonskitson** [comment]
Ok, I see the problem, will send a new binary.

**Comment by clintonskitson** [comment]
Try this one

https://drive.google.com/file/d/0B6vlRdQM169uNmVGb3l2VWFYWjQ/view?usp=sharing

**Comment by maricaantonacci** [comment]
I see again /usr/bin/xenstore-read...

<pre>
DEBU[0000] updated log level                             logLevel=debug
DEBU[0000] getting driver instances                      driverInitFuncs=map[linux:0x6a6460] driverNames=[linux]
DEBU[0000] os driver initialized                         provider=linux
DEBU[0000] initialized driver                            driverName=linux
DEBU[0000] getting driver instances                      driverInitFuncs=map[ec2:0x6a8d70 Openstack:0x6b31b0 Rackspace:0x6c5ec0 ScaleIO:0x6d7c40 XtremIO:0x6e3bf0] driverNames=[openstack]
DEBU[0000] error initializing driver                     driverName=Openstack error.provider=Openstack error.cmd.Path="/usr/bin/xenstore-read" error.cmd.Args=[/usr/bin/xenstore-read vm-data/provider_data/region] error.cmd.Out=[] error.message="error getting instance region"
Oops, an error occured!

  no storage drivers initialized
</pre>

**Comment by clintonskitson** [comment]
Are you doing `./rexray` to ensure you use the latest bin?

**Comment by clintonskitson** [comment]
Actually, I see the error.  It is stopping at a region lookup after the instance lookup now.

**Comment by clintonskitson** [comment]
Is there a region ID available from another command?

**Comment by maricaantonacci** [comment]
can be provided by a new option --openstackRegionName (like in Aws case)?

**Comment by clintonskitson** [comment]
Try this one.. https://drive.google.com/file/d/0B6vlRdQM169uZE9abmNDOEhMSnM/view?usp=sharing

There is now an `--OpenstackRegionName` option which bypasses the local lookup.

**Comment by maricaantonacci** [comment]
Sorry, maybe there's a mistake in the link: you shared the same patch as before (md5sum a6789bb03e8345a6854eef4cbf440022 match)
Error: unknown flag: with both --openstackRegionName and --OpenstackRegionName

**Comment by clintonskitson** [comment]
https://drive.google.com/file/d/0B6vlRdQM169uVXNQaDQxZWt3Xzg/view?usp=sharing

**Comment by clintonskitson** [comment]
https://drive.google.com/file/d/0B6vlRdQM169uMlpwcWRDdE1kTk0/view?usp=sharing

**Comment by clintonskitson** [comment]
https://drive.google.com/file/d/0B6vlRdQM169ubDBXX044YlNhdmM/view?usp=sharing

**Comment by clintonskitson** [comment]
https://drive.google.com/file/d/0B6vlRdQM169ubDBXX044YlNhdmM/view?usp=sharing

**Comment by clintonskitson** [comment]
https://drive.google.com/file/d/0B6vlRdQM169udWl0dXJ6NEh0Y00/view?usp=sharing

**Comment by clintonskitson** [comment]
https://drive.google.com/file/d/0B6vlRdQM169uREN5RW9WRGxqS0k/view?usp=sharing

**Comment by clintonskitson** [comment]
https://drive.google.com/file/d/0B6vlRdQM169uSzM3Z1FkMFRPbUE/view?usp=sharing

**Comment by maricaantonacci** [comment]
the problem now is the region name that is upper-case and therefore no endpoint is found for the compute service:
<pre>
INFO[0000] {Type: Name: Region:RECAS-CLOUD Availability:} 
PANI[0000] No suitable endpoint could be found in the service catalog. 
panic: No suitable endpoint could be found in the service catalog. [recovered]
</pre>
Note my region name is "recas-cloud"

**Comment by clintonskitson** [comment]
https://drive.google.com/file/d/0B6vlRdQM169uLVFDVGJrR3k3VHc/view?usp=sharing

**Comment by clintonskitson** [comment]
https://drive.google.com/file/d/0B6vlRdQM169uZmljX2k0TUZNUVU/view?usp=sharing

**Comment by clintonskitson** [comment]
https://drive.google.com/file/d/0B6vlRdQM169uSWxrb1MzbmVfdzg/view?usp=sharing

**Comment by clintonskitson** [comment]
https://drive.google.com/file/d/0B6vlRdQM169uWWxzRG92ajhiSmM/view?usp=sharing

**Comment by clintonskitson** [comment]
https://drive.google.com/file/d/0B6vlRdQM169udkZRNHI3TC1EdDg/view?usp=sharing

**Comment by clintonskitson** [comment]
https://drive.google.com/file/d/0B6vlRdQM169uTXdYbXRBUXFESUE/view?usp=sharing

**Comment by clintonskitson** [comment]
https://github.com/clintonskitson/rexray/tree/patch/openstack

**Comment by clintonskitson** [comment]
Reviewing the changes that were necessary to enable this to work for Openstack.  @akutz I will be breaking bugfixes out to other issues.

1) Duplicate Rackspace package into new area
2) Bug https://github.com/emccode/rexray/blob/master/storage/rackspace/storage.go#L164-L175 (config -> cfg)
3) Device name to `/dev/vd` from `/dev/xvd`
4) Min vol size not relevant in Openstack https://github.com/emccode/rexray/blob/master/storage/rackspace/storage.go#L28
5) getInstance changes due to KVM https://github.com/clintonskitson/rexray/blob/patch/openstack/storage/openstack/storage.go#L72-L89
6) allow region to be specified manually https://github.com/clintonskitson/rexray/blob/patch/openstack/storage/openstack/storage.go#L72-L89
7) do not force upper https://github.com/clintonskitson/rexray/blob/patch/openstack/storage/openstack/storage.go#L134

The items drive towards Openstack and Rackspace drivers not actually being much different.  I wonder if the best way to pursue this is to tackle a couple of things 1) Can we discovery instance and region based on KVM/Xen #5 #6? 2) Can we do better for local device discovery #3?

**Comment by clintonskitson** [comment]
This branch includes a specific commit for deltas between rackspace and openstack driver. https://github.com/clintonskitson/rexray/tree/patch/openstack_driver

**Comment by clintonskitson** [comment]
@maricaantonacci We have merged the Openstack driver.  If you are satisfied that it works as expected can you close the ticket?

`curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -s unstable latest -`

**Comment by clintonskitson** [comment]
```

**Comment by maricaantonacci** [comment]
rexray works fine with openstack! 
Currently I am trying to configure my mesos slaves to use the dvdi module but it seems there are some problems. Do you know if it works with the latest version of mesos (0.24.1 or 0.25)?

**Comment by clintonskitson** [comment]
The `mesos-module-dvdi` currently is only targeted at 0.23.0 and 0.23.1.  There were changes in the isolator interface for 0.24 and 0.25 which requires work to ensure compatibility.  The work for this is going to begin shortly.
