### ISSUE TITLE
Add Google Compute Engine Support

### ISSUE THREAD

**Issue by saturnism** [emccode/rexray#113]
Add driver for GCE disk. :)

**Comment by clintonskitson** [comment]
Thanks for the interest @saturnism.  I believe this wasn't done earlier due to GCE limitations.  It does look like the introspection and disk capabilities are in place now.  From a high level it does seem doable.  We will investigate further.  Otherwise, it would be a welcome PR.

**Comment by saturnism** [comment]
Let me know if you have any questions regarding the API as well! Feel free
to ping me on Twitter @saturnism

**Comment by clintonskitson** [comment]
https://github.com/emccode/rexray/pull/194

**Comment by clintonskitson** [comment]
Thanks for the update to Docker docs @saturnism!
