### ISSUE TITLE
Failed storage discovery results in panic

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#114]
When no storage drivers are discovered, it looks like a panic is created today.

```
root@cloud-server-01:~# rexray volume
Oops, an error occured!

  no storage drivers initialized

To correct the error please review:

  - Debug output by using the flag -l debug
  - The REX-ray website at https://github.com/emccode/rexray
  - The on↓ine he↓p be↓ow

Get one or more volumes

Usage: 
  rexray volume get [flags]

Aliases:
  get, list

Flags:
      --volumeid="": volumeid
      --volumename="": volumenamePANI[0000] runtime error: invalid memory
```

```
./rexray version
Binary: /root/rexray
SemVer: 0.2.1-dev+14+dirty
OsArch: Linux-x86_64
Branch: patch/rackspace_config
Commit: 33a3915e78950545c39de4e27b1e1da7d0d08fe6
Formed: Mon, 12 Oct 2015 20:08:08 UTC
```

**Comment by akutz** [comment]
Hi @clintonskitson,

Can you possibly help me debug this? I've looked at it quite a bit already, and I could not find anything that stuck out.

**Comment by clintonskitson** [comment]
will do @akutz

**Comment by clintonskitson** [comment]
Possibly as simple as https://github.com/clintonskitson/rexray/tree/bugfix/panic_for_help

**Comment by akutz** [comment]
Hi @clintonskitson,

This would make sense except for [this line](https://github.com/clintonskitson/rexray/commit/46874d3851a44ba6f09dfd12928a69df3c6072ab#diff-a5dcc678817453c5ff7954a28a095f2cR77). I'm not sure how that works out logically. Also, the reason it makes sense is because I had to update the Cobra templates and help logic after rebasing the help flag fix onto the latest Cobra master work.

**Comment by akutz** [comment]
Hi @clintonskitson,

Also, thank you for looking into this. I totally missed that somehow.

**Comment by clintonskitson** [comment]
The line is Atom doing what it does..

**Comment by clintonskitson** [comment]
https://github.com/emccode/rexray/pull/125

**Comment by akutz** [comment]
Hi @clintonskitson,

That doesn't make sense to me. Do you mean it's go's linter doing what it does?

**Comment by akutz** [comment]
I was talking about line #77

**Comment by akutz** [comment]
Hi @clintonskitson,

Nevermind. I'm still way too out of it.
