### ISSUE TITLE
Documentation overhaul

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#120]
Any @emccode/devhigh5 or @emccode/team members interested in assisting in a documentation overhaul for REX-Ray?

We are interested in ensuring a concise and minimal amount of information is present on the REX-Ray `README.md` page.  From there we should be breaking architecture information, detailed runtime, and driver information into separate pages.

Example configuration files would also be welcome based on the new `config.yml` structure.

**Comment by akutz** [comment]
Hi Clint,

I overhauled the docs on a branch I posted to slack two weeks ago. At least a starting point. We should start with that. It would have been completed by now but you've been asking me to work on DVDCLI and the Mesos DVDI module.

-- 
-a

**Comment by clintonskitson** [comment]
Yup, all good.  I believe this the droid that @akutz is referring to
https://github.com/akutz/rexray/tree/feature/trim-readme

**Comment by clintonskitson** [comment]
And a followup pointing to another little open source project that does a decent job at breaking things up in MD and then using a separate tool later on.  IMO, just breaking things into directories would be a good step #1.

https://github.com/docker/docker/tree/master/docs

**Comment by akutz** [comment]
Related to #145
