### ISSUE TITLE
amazon: support empty AWS_ACCESS_KEY and iam-instance-profile

### ISSUE THREAD

**Issue by jaroslavl1** [emccode/rexray#123]
On amazon when you create ec2 instance you can supply iam-instance-profile that has certain permissions. When using aws cli from such an instance there is no need for AWS_ACCESS_KEY and AWS_SECRET_KEY to be set anymore.

Rexray currently requires AWS_ACCESS_KEY and AWS_SECRET_KEY to be configured otherwise you get:

core@ip-10-60-130-21 ~ $ rexray volume get
FATA[0000] Error: Driver Volume discovery failed: AWS was not able to validate the provided access credentials (AuthFailure)

**Comment by clintonskitson** [comment]
Similar to https://github.com/emccode/rexray/issues/112

@jaroslavl1 I agree with you here, I believe we could implement the IAM feature in `goamz` and remove the necessity to supply creds on the instances.

**Comment by taik0** [comment]
This would be something very nice to have. All my instances use instance-profiles and don't want to have keys in my repos.

+1

**Comment by clintonskitson** [comment]
This support was added in 0.3.3 via https://github.com/emccode/rexray/pull/359
