### ISSUE TITLE
Creating a volume from an existing volume by default sets 16GB size

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#129]
When creating a new volume from an existing volume, currently the results depend on the provider.  For EC2, it allows arbitrary settings for size, volume type, etc.  Currently, if you don't specify these settings, default values will be assumed.

Consistent behavior for this between driver would be ideal, where initially at least replicating the settings within the new volume would take place.  Otherwise, it should be left to the driver to determine if they respect custom settings that are provided.

**Comment by akutz** [comment]
Hi @clintonskitson,

Would you like help on this? If so, can you describe the issue in more detail? Thanks!
