### ISSUE TITLE
Support JSON output

### ISSUE THREAD

**Issue by jaroslavl1** [emccode/rexray#135]
It ideally should be possible to select JSON as output instead of YAML. The reason is processing YAML in bash scripts is quite problematic. If you don't have a linux distribution where you can install Python, Perl etc (so something like CoreOS) you are very limited in processing tools you can use. You could of course do it inside Docker image, but it seems unnecessary to create docker image just to be able to parse YAML.

Fortunately there is YAML 2 JSON converter - https://github.com/bronze1man/yaml2json in Go and the JSON can be processed using JQ - https://stedolan.github.io/jq , both of these can be easily installed also on something like CoreOS since they have no dependencies.

YAML is definitely more readable, but for scripting its better to use JSON.

**Comment by clintonskitson** [comment]
@jaroslavl1 thanks for the feedback.  I can appreciate that and will leave this issue open.

**Comment by akutz** [comment]
Hi @jaroslavl1,

@clintonskitson tested this and says it looks good. We merged it to `master`.
