### ISSUE TITLE
Support master/agent REX-Ray mode

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#138]
In the future it may be desirable to have REX-Ray optionally function in a master/agent configuration.  

- Master REX-Ray lives on storage platform
- Master controls elevated privileges
- Master serves profiles that simplify or limit consumption
- Agent exposes local sockets (docker) and performs localized operations (instance/device discovery, format, mount)

Let's take an example of a single Docker instance.  The consumer of the Docker instance may want to add volume capabilities.  Currently, the credentials to the storage platform determine what access the user may have.  A `profile` capability in a central RR instance would enable a control mechanism that would limit a consumer to a subset of a storage platform performing a form of tenancy.

The credentials of the client can be based on the RR client instance, or could also be specified as a volume option.

`docker run --volume-driver=rexray -v test:/test busybox` (create,mount)
- Create
1) Invokes a HTTP socket request to `/run/docker/plugins/rexray.sock` for Create based on `name` and `options`
2) Invokes a HTTP socket request to RR master

- Mount
1) Local REX-Ray instance will perform instance discovery
2) Local REX-Ray will request volume attach from master sending `instanceID`
3) Master REX-Ray will reply with `network name` to discovery locally
4) Local REX-Ray will discover with `network name`
5) Local REX-Ray will format
6) Local REX-Ray will mount

Changes?
- RR master/agent needs storage platform drivers aware of split responsibilities
- RR master/agent API (libStroage API?)
- RR profiles

**Comment by akutz** [comment]
Hi @clintonskitson, would you like to handle this closure? This has been your vision come to fruition, so you should do the honors.

**Comment by clintonskitson** [comment]
Yes I will, thank you!
