### ISSUE TITLE
Panic when retrieving service module instances without RR daemon running

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#148]
If the RR daemon is not started (rexray start), and a command is run to get the running service module instances, a panic is created.

```
[root@mdm1 centos]# rexray service module instance get
PANI[0000] Get http://:7979/r/module/instances: dial tcp :7979: getsockopt: connection refused 
panic: Get http://:7979/r/module/instances: dial tcp :7979: getsockopt: connection refused [recovered]
	panic: Get http://:7979/r/module/instances: dial tcp :7979: getsockopt: connection refused [recovered]
```

**Comment by akutz** [comment]
This is not a bug, and is by design. Just because it's listed as a `panic`, it still indicates that the server is refusing the connection because it's not available. If you'd like to re-open as an Enhancement and restate the issue as asking for friendlier errors, then that's fine.
