### ISSUE TITLE
error when doing 'rexray volume list'

### ISSUE THREAD

**Issue by drumulonimbus** [emccode/rexray#163]
On Ubuntu 14.04LTS, using Docker 'experimental', when I issue `rexray volume list`, I see the following error:

> ubuntu@ip-172-31-7-127:~$ rexray volume list
> ERRO[0000] error parsing REXRAY_MOCKDRIVERS              REXRAY_MOCKDRIVERS= error=strconv.ParseBool: parsing "": invalid syntax

**Comment by clintonskitson** [comment]
Drew,

Can you add some more details here?

**Comment by akutz** [comment]
He has to be using the unstable build of Rex Ray. Still, I haven't seen that error when I run it, even though I know the code to which its referring 

-- 
-a

**Comment by drumulonimbus** [comment]
I've blown away the test instance I was using and have gone back to stable
releases of both rexray and docker - I can re-do it later on with the
experimental and unstable releases if you like.

Cheers,
- Drew.

--
Drew Smith (mux) <drew@riotnrrd.com>, VA7DSX / VE0TF
Encrypted e-mail preferred, public key at http://riotnrrd.com/pubkey.gpg

**Comment by akutz** [comment]
Fixed with PR #164.
