### ISSUE TITLE
Docker reports a plugin error when creating a container for name exceeding length

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#17]
There is a parameter in a Dockerfile where it specifies a certain amount of external volumes be used.  Currently in Docker 1.7+, you can specify extra volumes using the runtime flag of ```-v```, but this does not override volumes that are specified in the ```Dockerfile```.  Once you pass the ```--volume-driver``` flag, all volumes that are associated are passed to the plugin.  In the following case there is one volume that is specified attached to ```/var/lib/mysql```.

```docker run -ti --name mysql7 -p 3306:3306 -e MYSQL_PASS="87654321" --volume-driver=rexray -v wpmsql01c:/var/lib/mysql tutum/mysql```

If you look at the ```Dockerfile``` you will see that the volume statement includes two volumes as ```VOLUME  ["/etc/mysql", "/var/lib/mysql"]```.  This causes Docker to try and create a new volume for ```/etc/mysql``` since this volume based on mount point is not specified at runtime.  A new GUID is created and a new volume is created and attach to this mount point.

The error as ```Error response from daemon: Plugin Error: {"Error":"problem getting response: The given name exceeds the allowed length of 31 characters."}``` is coming up since the ScaleIO driver currently only supports up to 31 characters in the name of a volume.

FIX: Ensure that you specify the same number of volumes or more than the number specified in the Dockerfile under ```volumes```.  The mount point path in the Dockerfile must correlate to the mount point path under the ```-v``` flags.

**Comment by clintonskitson** [comment]
The PR for Docker is https://github.com/docker/docker/pull/15507 to fix this issue.

**Comment by akutz** [comment]
I'm closing this issue as it's labeled wontfix. If the status changes we can re-open it.

**Comment by akutz** [comment]
Hi @clintonskitson, 

So issue #24 references this issue which references PR https://github.com/docker/docker/pull/15507 which is merged. Does that mean this issue can be closed? Can #24 be closed?
