### ISSUE TITLE
rexray can not volume attach on openstack 

### ISSUE THREAD

**Issue by HackToday** [emccode/rexray#179]
I settup rexray, with rexray I can create volume, but when running 
$ sudo rexray volume  get
- name: myvoltest
  volumeid: 0a9c53b7-97f2-4369-8d62-43a2885c6be8
  availabilityzone: nova
  status: available
  volumetype: lvmdriver-1
  iops: 0
  size: "1"
  networkname: ""
  attachments: []
- name: k8sbay-rrpxyj5mdyqp-kube_minions-r3taoivuiqp5-0-dugpbsrwtsvz-docker_volume-mgxn6adbyjom
  volumeid: 5b727c81-8afc-4038-83bb-a6f627cc8940
  availabilityzone: nova
  status: in-use
  volumetype: lvmdriver-1
  iops: 0
  size: "4"
  networkname: ""
  attachments:
  - volumeid: 5b727c81-8afc-4038-83bb-a6f627cc8940
    instanceid: 502db7fb-c2ed-44a0-a2ac-9f7180fd22dc
    devicename: /dev/vdb
    status: ""

Following errors for volume attach 
$ sudo rexray volume  attach --volumeid=0a9c53b7-97f2-4369-8d62-43a2885c6be8
PANI[0001] interface conversion: interface is nil, not volumeattach.VolumeAttachmentsPage 
panic: interface conversion: interface is nil, not volumeattach.VolumeAttachmentsPage [recovered]
	panic: interface conversion: interface is nil, not volumeattach.VolumeAttachmentsPage [recovered]
	panic: (*logrus.Entry) (0xa75780,0xc82019de80)

goroutine 1 [running]:
github.com/Sirupsen/logrus.Entry.log(0xc82006e140, 0xc8202384b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc8201bc230, ...)
	/home/travis/gopath/src/github.com/Sirupsen/logrus/entry.go:113 +0x618
github.com/Sirupsen/logrus.(*Entry).Panic(0xc820230df0, 0xc820230ed8, 0x1, 0x1)
	/home/travis/gopath/src/github.com/Sirupsen/logrus/entry.go:158 +0x99
github.com/Sirupsen/logrus.(*Logger).Panic(0xc82006e140, 0xc820230ed8, 0x1, 0x1)
	/home/travis/gopath/src/github.com/Sirupsen/logrus/logger.go:157 +0xe7
github.com/Sirupsen/logrus.Panic(0xc820230ed8, 0x1, 0x1)
	/home/travis/gopath/src/github.com/Sirupsen/logrus/exported.go:107 +0x41
github.com/emccode/rexray/rexray/cli.(*CLI).Execute.func1()
	/home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:187 +0x2e0
github.com/emccode/rexray/rexray/cli.(*CLI).execute.func1()
	/home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:206 +0xd4
github.com/rackspace/gophercloud/openstack/compute/v2/extensions/volumeattach.ExtractVolumeAttachments(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/rackspace/gophercloud/openstack/compute/v2/extensions/volumeattach/results.go:39 +0x8b
github.com/emccode/rexray/drivers/storage/openstack.(*driver).getBlockDevices(0xc820095e00, 0xc8201babd0, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/emccode/rexray/drivers/storage/openstack/openstack.go:240 +0x13e
github.com/emccode/rexray/drivers/storage/openstack.(*driver).GetVolumeMapping(0xc820095e00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/emccode/rexray/drivers/storage/openstack/openstack.go:208 +0x80
github.com/emccode/rexray/drivers/storage/openstack.(*driver).GetDeviceNextAvailable(0xc820095e00, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/emccode/rexray/drivers/storage/openstack/openstack.go:754 +0x131
github.com/emccode/rexray/drivers/storage/openstack.(*driver).AttachVolume(0xc820095e00, 0xc8201a6a00, 0x7fff9a143967, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/emccode/rexray/drivers/storage/openstack/openstack.go:820 +0x2c3
github.com/emccode/rexray/core.(*sdm).AttachVolume(0xc8202357c0, 0xc820236200, 0x7fff9a143967, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/emccode/rexray/core/drivers_storage.go:375 +0x118
github.com/emccode/rexray/rexray/cli.(*CLI).initVolumeCmds.func6(0xc8201a4380, 0xc8201a0d40, 0x0, 0x1)
	/home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cmds_volume.go:129 +0x100
github.com/emccode/rexray/vendor/github.com/spf13/cobra.(*Command).execute(0xc8201a4380, 0xc8201a0ce0, 0x1, 0x1, 0x0, 0x0)
	/home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/spf13/cobra/command.go:534 +0x869
github.com/emccode/rexray/vendor/github.com/spf13/cobra.(*Command).Execute(0xc820100540, 0x0, 0x0)
	/home/travis/gopath/src/github.com/emccode/rexray/vendor/github.com/spf13/cobra/command.go:617 +0x46a
github.com/emccode/rexray/rexray/cli.(*CLI).execute(0xc82015a900)
	/home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:210 +0x42
github.com/emccode/rexray/rexray/cli.(*CLI).Execute(0xc82015a900)
	/home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:193 +0x3e
github.com/emccode/rexray/rexray/cli.Execute()
	/home/travis/gopath/src/github.com/emccode/rexray/rexray/cli/cli.go:167 +0x25
main.main()
	/home/travis/gopath/src/github.com/emccode/rexray/rexray/rexray.go:11 +0x14

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 21 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 34 [IO wait]:
net.runtime_pollWait(0x7f52fc4ab718, 0x72, 0xc820072080)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201ca1b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201ca1b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201ca150, 0xc8201c7000, 0x1000, 0x1000, 0x0, 0x7f52fc4a5028, 0xc820072080)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8201dc000, 0xc8201c7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f52fc02d050, 0xc8201dc000, 0xc8200d79c8, 0xc8201c7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8201da040, 0xc8201c7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8201e0000)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8201e0000, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200d7970)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 35 [select]:
net/http.(*persistConn).writeLoop(0xc8200d7970)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 3 [IO wait]:
net.runtime_pollWait(0x7f52fc4ab658, 0x72, 0xc820072080)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82023a140, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82023a140, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82023a0e0, 0xc82023c000, 0x1000, 0x1000, 0x0, 0x7f52fc4a5028, 0xc820072080)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82002c008, 0xc82023c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f52fc02d050, 0xc82002c008, 0xc8200d7a78, 0xc82023c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc820016160, 0xc82023c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820018120)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820018120, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200d7a20)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 4 [select]:
net/http.(*persistConn).writeLoop(0xc8200d7a20)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

**Comment by clintonskitson** [comment]
@HackToday Do you have the version information about your Cinder instance?  The error that you are hitting is from a package we are using the gives us the OpenStack bindings.  It looks like the response coming from Cinder doesn't include the paging as expected.

**Comment by HackToday** [comment]
Hi @clintonskitson  I am using devstack to setup openstack environment. Not sure if you know devstack , it is kind of dev tools to help setup all-in-one openstack environment

**Comment by clintonskitson** [comment]
@HackToday Please close this issue if you are satisfied, thanks.

https://github.com/emccode/rexray/issues/178

**Comment by HackToday** [comment]
thanks @clintonskitson  I will close this
