### ISSUE TITLE
rexray volume dirver can not work with docker run command [openstack cloud]

### ISSUE THREAD

**Issue by HackToday** [emccode/rexray#181]
I tried following case::

[fedora@swarmbay-5rmzmkagfclk-swarm-master-ug2djpfuuwit ~]$ sudo ./rexray volume  create --volumename="testok" --size 1
name: testok
volumeid: 41f54bcf-98e8-47f7-b501-42349bcc100f
availabilityzone: nova
status: available
volumetype: lvmdriver-1
iops: 0
size: "1"
networkname: ""
attachments: []

[fedora@swarmbay-5rmzmkagfclk-swarm-master-ug2djpfuuwit ~]$ sudo ./rexray volume  mount --volumename=testok                            
/var/lib/rexray/volumes/testok

The above command are OK, But following would fail:

[fedora@swarmbay-5rmzmkagfclk-swarm-master-ug2djpfuuwit ~]$ sudo docker -D -H tcp://127.0.0.1:2376 --tlsverify --tlscacert="/etc/docker/ca.crt" --tlskey="/etc/docker/server.key" --tlscert="/etc/docker/server.crt" run -ti --volume-driver=rexray -v testwork:/test1 busybox
DEBU[0000] Trusting certs with subjects: [010U
                                                   swarmbay] 
Error response from daemon: 500 Internal Server Error: Plugin Error: {"Error":"error getting driver instance"}

**Comment by HackToday** [comment]
BTW: I used docker swarm.

**Comment by clintonskitson** [comment]
Can you manually check that each of the hosts works with the volume driver before trying against swarm?  This was tested so there should not be a problem if each docker host is working properly.

**Comment by HackToday** [comment]
It was volume size issue, as for rexray support docker 1.8,  use docker 
docker run -ti --volume-driver=rexray -v test:/test busybox

it would default to 16G, so either upgrade to docker 1.9 or use rexray to create volume first with specified size
