### ISSUE TITLE
running rexray for docker on osx: error=unknown OS

### ISSUE THREAD

**Issue by kbroughton** [emccode/rexray#183]
The docs say osx is supported, but the only driverName is linux.
Should I be able to follow the main README on osx?
I have AWS_SECRET_KEY and AWS_ACCESS_KEY, AWS_REGION env vars set.
Here is my ~/.rexray/config.yml
    osDrivers:
     - linux
    volumeDrivers:
     - docker
    storageDrivers:
     - ec2

Commandline with sudo says must run as root.  With sudo:

sudo rexray -l debug -c ~/.rexray/config.yml volume get
Password:
DEBU[0000] updated log level                             logLevel=debug
INFO[0000] volume driver initialized                     provider=docker
DEBU[0000] error initializing driver                     driverName=linux error=unknown OS
DEBU[0000] error initializing driver                     driverName=ec2 error.provider=ec2 error.message="error getting instance id doc"

**Comment by clintonskitson** [comment]
Hello,

OSX is supported as a client for RR which means there is remoting
capabilities if RR was running on a remote server.

What are you trying to accomplish?

The main use case today is running as a service so Docker or Mesos can
orchestrate volume access.

**Comment by kbroughton** [comment]
I use docker-machine for local development.  I was just hoping to try out
docker + rexray on osx before testing on linux.   docker-machine uses a
virtualbox linux vm.  I was hoping the driver would get installed on the vm
and docker on OSx would be able to use it that way.  I tried installing via
the curl command on both osx and the docker-machine vm.  The storage
backend is EBS.

On Sun, Nov 22, 2015 at 12:34 PM, Clinton Kitson <notifications@github.com>
wrote:

> Hello,
>
> OSX is supported as a client for RR which means there is remoting
> capabilities if RR was running on a remote server.
>
> What are you trying to accomplish?
>
> The main use case today is running as a service so Docker or Mesos can
> orchestrate volume access.
>
>
> On Sunday, November 22, 2015, kesten <notifications@github.com> wrote:
>
> > The docs say osx is supported, but the only driverName is linux.
> > Should I be able to follow the main README on osx?
> > I have AWS_SECRET_KEY and AWS_ACCESS_KEY, AWS_REGION env vars set.
> > Here is my ~/.rexray/config.yml
> > osDrivers:
> > - linux
> > volumeDrivers:
> > - docker
> > storageDrivers:
> > - ec2
> >
> > Commandline with sudo says must run as root. With sudo:
> >
> > sudo rexray -l debug -c ~/.rexray/config.yml volume get
> > Password:
> > DEBU[0000] updated log level logLevel=debug
> > INFO[0000] volume driver initialized provider=docker
> > DEBU[0000] error initializing driver driverName=linux error=unknown OS
> > DEBU[0000] error initializing driver driverName=ec2 error.provider=ec2
> > error.message="error getting instance id doc"
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/emccode/rexray/issues/183>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emccode/rexray/issues/183#issuecomment-158787563>.
>



-- 
kesten broughton
devops @ cognitivescale

**Comment by clintonskitson** [comment]
If there was a virtual box driver then it would worked that is the direct
layer under the docker instance.  If your docker instance is on a Linux
system without virtual box then it would work fine.

**Comment by akutz** [comment]
@kbroughton,

So part of the issue is actually that the Docker Golang library has these mount packages for which nothing is yet implemented for Darwin (OS X). The same for Windows. Docker is *heavily* Linux only, and even Golang to an extent (although the latter largely works for Darwin as well). I toyed around with using MacFuse to enable REX-Ray storage on Darwin, but it ended up being more trouble than it was worth thanks to the inconsistency in the Docker golang code. 

FWIW, here is the [Docker package](https://github.com/docker/docker/tree/master/pkg/mount) to which I'm referring. As you can see, if you're not on Linux or FreeBSD, the mount info is unsupported.

![image](https://cloud.githubusercontent.com/assets/101085/11484580/648803f4-9774-11e5-8e74-b556d05a1f1d.png)
