### ISSUE TITLE
Compilation failure on OSX

### ISSUE THREAD

**Issue by gijzelaerr** [emccode/rexray#186]
When I try to compile current rexray on OSX I fail:
```
λ  cd rexray
λ  make
SemVer: 0.3.0-dev+10
RpmVer: 0.3.0+dev+10
Branch: master
Commit: b0729581afb9bbc8647e3a1fab558a16efc4ab01
Formed: Mon, 30 Nov 2015 11:22:49 SAST

target: deps
  ...installing glide...SUCCESS!
  ...downloading go dependencies...SUCCESS!
target: fmt
  ...formatting rexray...SUCCESS!
target: install
  ...installing rexray Darwin-x86_64...# github.com/emccode/rexray/core/config
core/config/config.go:202: c.v.ReadConfigNoNil undefined (type *viper.Viper has no field or method ReadConfigNoNil)
make: *** [_install] Error 2
make: Target `all' not remade because of errors.
λ  git describe
v0.2.1-10-gb072958
```

Unfortunately i'm absolutely unfamiliar with go, but please let me know if you need more debug information.

**Comment by akutz** [comment]
Hi @gijzelaerr,

This is a bug due to a dependency change. I'll be pushing a PR to accommodate this shortly.

**Comment by akutz** [comment]
Hi @gijzelaerr,

PR #188 has been filed that fixes this issue.

**Comment by gijzelaerr** [comment]
i can confirm this has solved the problem, thanks!

**Comment by akutz** [comment]
Hi @gijzelaerr,

You're very welcome. Please let me know if you run into any other issues :)
