### ISSUE TITLE
Use ec2 storage provider on vms not in EC2?

### ISSUE THREAD

**Issue by michaelarusso** [emccode/rexray#204]
Is it possible to use the ec2 storage provider in an environment not running within EC2?  Example, we have a multi-node cluster running locally with Vagrant/VirtualBox.  We need to be able to leverage development/testing locally with shared volumes across the nodes, and have same functionality after deploying to EC2.

I saw #104 is still open.  Is there any other way to leverage rexray in a local VM environment to have a shared volume across multiple VMs?

**Comment by clintonskitson** [comment]
@michaelarusso I think the clearest answer here would be to build a VirtualBox driver as @md5 had suggested.  I think it makes a ton of sense.  I will look at this in the short term.

Today, we do have support for Isilon.  This can be for used today with Fusion, but likely ported easily to a Virtual Box VM.  If that was fired up from a consistent point where it is pre-configured alongside the hosts then you'd have an easy way to advertise shared storage.

**Comment by clintonskitson** [comment]
BTW. the answer to the original question in the title is no.  It is an ec2 platform thing, where you can't consume ec2 storage unless you are running from an ec2 instance.  But I believe your description is more accurate which is basically asking if a driver can be created for virtualbox so that you have a consistent experience locally and in the cloud when using external volumes.

**Comment by clintonskitson** [comment]
Last question.. What features would you expect to work from the Virtual Box driver?

Snapshot
Pre-Emption
Create volume from snapshot
VolumeType

**Comment by michaelarusso** [comment]
Generally I think we'd look for some of the same higher level functionality that ec2 provides for EBS, just leveraging VirtualBox.

Also, what about support for a driver to interact with local Linux file system?  This way we could test even without VirtualBox the functionality and then push to AWS with different provider?

**Comment by clintonskitson** [comment]
If you are looking for all of the functionality, then it would need to leverage something that provides diffs.  A driver that uses Git or a layered filesystem like BTRFS or AUFS could fill the gap.  These though would not enable the cross-host capability of the external storage platforms or virtualization layers.

**Comment by clintonskitson** [comment]
Actually, I take that back.  You could do something similar (but not very efficiently) using a flat file system.  The VFS driver for Docker implements this where it just copies files between directories when it needs to copy volumes etc.

**Comment by clintonskitson** [comment]
@michaelarusso By the way, I am making some promising progress on a driver for VirtualBox.  Will update the thread with progress and something to test.

**Comment by michaelarusso** [comment]
@clintonskitson Thanks for the quick response!  I'll be happy to try it out when it's available.

**Comment by clintonskitson** [comment]
@michaelarusso @dm5 Here is the working driver!  See the docs in the PR if you are going to test it out.

https://github.com/emccode/rexray/pull/209

**Comment by clintonskitson** [comment]
Look for the 0.3.1 release shortly including the driver.

**Comment by clintonskitson** [comment]
VirtualBox 5.0.10+ support is in REX-Ray 0.3.1
