### ISSUE TITLE
The rexray service is failure when /rexray/config.yml about openstack driver write  both domainName and domainId at the same time.

### ISSUE THREAD

**Issue by wangqunOne** [emccode/rexray#205]
I use the rexray-Linux-x86_64-0.3.0.tar.gz
when writting the follow context in the /etc/rexray/config.yml. The rexray service is dead.
rexray:
  storageDrivers:
  - openstack
openstack:
  authUrl:              *****
  username:             admin
  password:             password
  tenantName:           admin
  regionName:           RegionOne
  availabilityZoneName: nova
  domainName:           Default
  domainID:                  default
If I remove the domainID, The rexray service can work well.

**Comment by wangqunOne** [comment]
@clintonskitson

**Comment by clintonskitson** [comment]
@wangqunOne I would assume that specifying the `domainID: default` would be an incorrect setting since it's a name as specified previously in `domainName: Default`?

**Comment by clintonskitson** [comment]
@wangqunOne Are you satisfied with the response here?  If so can you close the comment?

**Comment by wangqunOne** [comment]
@clintonskitson, I understand the issue for your explain.Thank you very much for your explain,
