### ISSUE TITLE
Improve documentation: add issues add suggestions as comments

### ISSUE THREAD

**Issue by cantbewong** [emccode/rexray#206]
Indicate order of precedence when configuration is in environment, and the two supported locations for .yml files. Which source wins when items are specified in multiple locations

Indicate the default location of log file

Indicate format, or examples of multiple valid values for AWS regions

Indicate how to install a version other than the latest. Indicate how to upgrade and how to roll back

**Comment by clintonskitson** [comment]
Keep the list coming, we will be tackling this as an action item next week.

**Comment by cantbewong** [comment]
Regarding engaging pre-emptive mounts, Assume the goal is that a mount is originally mounted to agent node-A, which crashes or is isolated, and then is to be pre-emptively mounted on agent node-B.

Is is necessary to configure:
1. Both node-A and node-B for pre-emptive mounts?
2 only target node-B?
3 only source node-A?

**Comment by clintonskitson** [comment]
Only the host initiating he pre emotive mount needs to be enabled for the
setting.  Once that host engages a mount the other host is unaware.

**Comment by clintonskitson** [comment]
- Main page
- Troubleshooting
 - `rexray env`
 - `rexray -l debug`
 - `rexray version`
- Configuration page
