### ISSUE TITLE
An error that no storages initialized occured when verigying that the cinder volume can work on the mesos by rexray.

### ISSUE THREAD

**Issue by wangqunOne** [emccode/rexray#218]
Hi, I am verifying if the cinder volume can work on the mesos by rexray. But the rexray failed during the install on the mesos. The follow is my process of installing the rexray on the mesos:
1. install rexray
2. config file in /etc/rexray/config.yml. The content of the config.yml is 
$cat /etc/rexray/config.yml
rexray:
  storageDrivers:
  - openstack
  volume:
    mount:
      preempt: true
openstack:
  authUrl:              http://*****/v3
  username:             admin
  password:             password
  tenantName:           admin
  regionName:           RegionOne
  availabilityZoneName: nova
  domainName:           Default
3.sudo rexray start

But I got an error occured. 
$sudo /rexray start -l -debug
INFO[0000] volume driver initialized                     provider=docker
INFO[0000] os driver initialized                         provider=linux
Oops, an error occured!

  no storage drivers initialized

To correct the error please review:

  - Debug output by using the flag -l debug
  - The REX-ray website at https://github.com/emccode/rexray
  - The on↓ine he↓p be↓ow

Start the service

Usage: 
  rexray service start [flags]

Flags:
      --client="": Socket the daemon uses to communicate to the client
      --force[=false]: Forces the service to start, ignoring errors
  -f, --foreground[=false]: Starts the service in the foreground

Global Flags:
  -c, --config="/root/.rexray/config.yml": The REX-Ray configuration file
  -?, --help[=false]: Help for start
  -h, --host="tcp://:7979": The REX-Ray service address
  -l, --logLevel="warn": The log level (panic, fatal, error, warn, info, debug)
  -v, --verbose[=false]: Print verbose help information

**Comment by wangqunOne** [comment]
@clintonskitson

**Comment by clintonskitson** [comment]
This was answered in Slack.  The problem was related to trying to use a RR 0.3 formatted config.yml on a 0.2 RR.  We should be stable now re that file.
