### ISSUE TITLE
Automation examples

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#224]
There should be a new tab that defines all of the automation for deploying RR.

- Cloud Formation
- Heat
- Vagrantfiles
- Chef
- Puppet
- Ansible
- Salt
- CF Engine

**Comment by akutz** [comment]
Please don't change the layout of the RTD site. It's delicate and tied to the custom theme I built. I specifically added the rulers to the User Guide tab per CSS to overcome this. It's a limitation of Markdown and mkdocs along with Bootstrap. We need to switch to RST for more complex tabs and layout, but Clint vetoed this idea when I suggested it. Not that I was its biggest fan either.

**Comment by akutz** [comment]
If you want to do anything then create a branch and edit the theme to incorporate sub-tabs using a fork of Bootstrap 3 or a Bootstrap 4 alpha. That's the right way to do it. I won't support more than the User and Dev Guides up top. Everything else should be sub-tabs/categories of those as they would be with RST

**Comment by clintonskitson** [comment]
We won't merge anything now.  This session is more about generating the content, and then we will figure out the proper place and right way to incorporate the new information that we created.

**Comment by drumulonimbus** [comment]
something like this perhaps?
https://github.com/drumulonimbus/rexray/blob/feature/docs_automation_examples/.docs/user-guide/automation.md

Cheers,
- Drew.

--
Drew Smith (mux) <drew@riotnrrd.com>, VA7DSX / VE0TF
Encrypted e-mail preferred, public key at http://riotnrrd.com/pubkey.gpg

**Comment by akutz** [comment]
Drew's example is perfect. To me "tab" refers to the top-level items in the header. The "Home", "User Guide," "Dev Guide," and "About."

Drew's item would fit under User Guide. I think Clint wants to create a peer to User Guide called Automation. Or that's what I would mean if I said tab.

I'd like to extend our theme to support horizontal menus that expand from items in the top-level tabs. For example, under User Guide there would be an item named "Storage Platforms" and it would expand when hovered to show all the providers that are currently direct children in User Guide.

**Comment by clintonskitson** [comment]
Frmaeword started https://github.com/emccode/rexray/pull/228
