### ISSUE TITLE
No volumes returned by name

### ISSUE THREAD

**Issue by djannot** [emccode/rexray#248]
Issue happening when creating a new container:
docker run -ti --volume-driver=rexray -v test:/test ubuntu bash

Centos 7 + Docker 1.9.1 + RexRay 0.3.1

Logs in debug mode:
time="2016-01-07T12:09:55-05:00" level=info msg="getting path to volume" driverName=docker volumeID= volumeName=test 
time="2016-01-07T12:09:55-05:00" level=debug msg="got instance" instance=&{ScaleIO 437ec66d00000004  } provider=ScaleIO 
time="2016-01-07T12:09:55-05:00" level=error msg="/VolumeDriver.Path: error returning path" error="No volumes returned by name" 
time="2016-01-07T12:09:55-05:00" level=error msg="No volumes returned by name" 
time="2016-01-07T12:09:55-05:00" level=info msg="mounting volume" driverName=docker newFsType= overwriteFs=false volumeID= volumeName=test 
time="2016-01-07T12:09:55-05:00" level=debug msg="got instance" instance=&{ScaleIO 437ec66d00000004  } provider=ScaleIO 
time="2016-01-07T12:09:55-05:00" level=error msg="/VolumeDriver.Mount: error mounting volume" error="No volumes returned by name" 
time="2016-01-07T12:09:55-05:00" level=error msg="No volumes returned by name" 
time="2016-01-07T12:09:55-05:00" level=info msg="status of count" exists=false volumeName=test 
time="2016-01-07T12:09:55-05:00" level=info msg="initialized count" count=0 volumeName=test 
time="2016-01-07T12:09:55-05:00" level=info msg="unmounting volume" driverName=docker volumeID= volumeName=test 
time="2016-01-07T12:09:55-05:00" level=debug msg="got instance" instance=&{ScaleIO 437ec66d00000004  } provider=ScaleIO 
time="2016-01-07T12:09:55-05:00" level=error msg="/VolumeDriver.Unmount: error unmounting volume" error="No volumes returned by name" 
time="2016-01-07T12:09:55-05:00" level=error msg="No volumes returned by name"

**Comment by clintonskitson** [comment]
Found the problem @djannot?

**Comment by djannot** [comment]
@clintonskitson This is the first time I try to use RexRay and thought the volume was automatically created when running a docker run, but I'm not sure, so I now try to create and mount the volume and I get another error (FATA[0024] read /dev/scinia: input/output error).

I'll investigate and see if I need to open another issue for this one. And then, I'll see if the docker run works

**Comment by clintonskitson** [comment]
Always good to start with the basics here.  The io error would refer to the device not actually being available.

`rexray volume create --volumename=testing --size=1"
`rexray volume mount --volumename=testing`
`rexray volume unmount --volumename=testing`

**Comment by djannot** [comment]
The issue was related to a communication problem between the SDC and the MDM.
Everything works perfectly now.

**Comment by akamalov** [comment]
Exhibiting the same problem as shown above. Communication between SDC and MDM work fine:

```
Query-all-SDS returned 4 SDS nodes.

Protection Domain d3d552e900000000 Name: domain1
SDS ID: 307f211e00000003 Name: node262 State: Connected, Joined IP: XXX.XXX.1.96 Port: 7072
SDS ID: 307f211d00000002 Name: node263 State: Connected, Joined IP: XXX.XXX.1.97 Port: 7072
SDS ID: 307f211c00000001 Name: node261 State: Connected, Joined IP: XXX.XXX.1.95 Port: 7072
SDS ID: 307f211b00000000 Name: node264 State: Connected, Joined IP: XXX.XXX.1.98 Port: 7072
[root@node236 ~]# 
```
Also, issuing manual volume create, mount, unmount, remove work normally. However, when issued to create a volume as part of json file to Mesos, Mesos-Slave rexray starts exhibiting the problem (it used to work fine, now its not):

```
[root@node262 ~]# systemctl -l status rexray
● rexray.service - rexray
   Loaded: loaded (/etc/systemd/system/rexray.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2016-02-02 12:11:48 EST; 12min ago
 Main PID: 23502 (rexray)
   Memory: 6.8M
   CGroup: /system.slice/rexray.service
           └─23502 /usr/bin/rexray start -f

Feb 02 12:11:48 node262.localnet.net rexray[23502]: OsArch: Linux-x86_64
Feb 02 12:11:48 node262.localnet.net rexray[23502]: Branch: v0.3.1
Feb 02 12:11:48 node262.localnet.net rexray[23502]: Commit: bf4d6eec8c931b10d1ec187de052a23c09681ac6
Feb 02 12:11:48 node262.localnet.net rexray[23502]: Formed: Wed, 30 Dec 2015 16:12:44 EST
Feb 02 12:17:43 node262.localnet.net rexray[23502]: time="2016-02-02T12:17:43-05:00" level=error msg="/VolumeDriver.Unmount: error unmounting volume" error="No volumes returned by name"
Feb 02 12:17:43 node262.localnet.net rexray[23502]: time="2016-02-02T12:17:43-05:00" level=error msg="No volumes returned by name"
Feb 02 12:19:21 node262.localnet.net rexray[23502]: time="2016-02-02T12:19:21-05:00" level=error msg="/VolumeDriver.Unmount: error unmounting volume" error="No volumes returned by name"
Feb 02 12:19:21 node262.localnet.net rexray[23502]: time="2016-02-02T12:19:21-05:00" level=error msg="No volumes returned by name"
Feb 02 12:23:41 node262.localnet.net rexray[23502]: time="2016-02-02T12:23:41-05:00" level=error msg="/VolumeDriver.Unmount: error unmounting volume" error="No volumes returned by name"
Feb 02 12:23:41 node262.localnet.net rexray[23502]: time="2016-02-02T12:23:41-05:00" level=error msg="No volumes returned by name"
[root@node262 ~]# 
```

Restarted rexrat daemon on all nodes, but it is not helping.

**Comment by clintonskitson** [comment]
@akamalov Can you verify that the volume that you are targeting is a part of the correct `storage pool`?  In the `0.3.1` version, the ScaleIO driver is configured against a single storage pool.  If trying to access volumes outside of that pool, then the error would make sense.  If this is the case, we have a PR open to work with all pools regardless of the configured one.

**Comment by akamalov** [comment]
Not sure what you mean, Clint.  Are you saying that a volume must be manually pre-created ? Here is the json file which I use to submit it to Mesos.
```
{
 "id": "nginx2rexray",
 "container": {
 "docker": {
 "image": "million12/nginx",
 "network": "BRIDGE",
 "portMappings": [
 { "containerPort": 80, "hostPort": 0, "protocol": "tcp"}
 ],
 "parameters": [
 { "key": "volume-driver", "value": "rexray" },
 { "key": "volume", "value": "nginx-data:/data/www" }
 ]
 }
 },
 "cpus": 0.2,
 "mem": 32.0,
 "instances": 1
}

```

**Comment by akamalov** [comment]
It's from the article: http://blog.emccode.com/2015/08/28/run-your-stateful-apps-with-mesos-and-docker/

**Comment by clintonskitson** [comment]
Ok, I see what you're asking.  The volume should be created automatically.

From the error that you sent over, it looks like it's trying to unmount the volume and running into an error since it doesn't exist anymore.  

Can you chance the `nginx-data` to another name and try submitting again?

**Comment by akamalov** [comment]
OK. Solved. I don't know if I can say it that way...However, I had to restart the Mesos-Slave. Once restarted, I was able to deploy volumes as per example posted.

**Comment by clintonskitson** [comment]
@akamalov FYI, one more piece of info here.  In Docker 1.9 volume existence
is currently a part of the engine.  If a volume got deleted in the backend
without doing it through the volume interface then Docker will have
problems accessing the volume subsequently even if created net new.  Docker
1.10 includes an enhancement to ensure all volume knowledge comes from the
platform to eliminate this problem.

See PR https://github.com/emccode/rexray/pull/274
