### ISSUE TITLE
Website typo

### ISSUE THREAD

**Issue by ktruckenmiller** [emccode/rexray#252]
http://rexray.readthedocs.org/en/stable/#getting-help

The /etc/rexray file should be called 'config.yml' not 'rexray.yml'

It won't start unless it's config.yml. :)

**Comment by clintonskitson** [comment]
Thanks @ktruckenmiller.

We have a PR at https://github.com/emccode/rexray/pull/251 to update this.  Sorry for the confusion.  Can you close if satisfied?
