### ISSUE TITLE
Virtualbox error creating volume

### ISSUE THREAD

**Issue by byrnedo** [emccode/rexray#255]
I'm trying to use rexray on a docker swarm which is running on boot2docker images.
It's all running on virtualbox.

I have virtualbox version 5.0.10_Ubuntu r104061

The vbox daemon is running:

    vboxwebsrv -H 0.0.0.0 -v

I have installed rexray on all nodes and the config looks like so:

    rexray:
      logLevel: warm
      storageDrivers:
      - virtualbox
      volume:
        mount:
          preempt: false
    virtualbox:
      endpoint: http://10.0.2.2:18083
      volumePath: /home/donal/VirtualBoxVolumes 
      controllerName: SATA

But when I try an create a volume:

    $docker volume create --driver=rexray --name=mongo --opt=size=5
        Error response from daemon: Plugin Error: VolumeDriver.Create, {"Error":"open /dev/disk/by-id: no such file or directory"}

Rexray service logs show:

    time="2016-01-13T14:35:14Z" level=error msg="/VolumeDriver.Create: error creating volume" error="open /dev/disk/by-id: no such file or directory" 
    time="2016-01-13T14:35:14Z" level=error msg="open /dev/disk/by-id: no such file or directory" 

Any idea what's going wrong?

**Comment by clintonskitson** [comment]
Yeah, I ran into the same recently with boot2docker as well.

The issue https://github.com/boot2docker/boot2docker/issues/1111 should
describe what I found.

Basically udev isn't creating necessary paths for devices to allow rexray
to discover as it needs to.

**Comment by byrnedo** [comment]
Ok, thanks for the infor, any workaround right now?

**Comment by clintonskitson** [comment]
Would be great to enable some Docker Toolbox use cases, but unfortunately
not yet.  I raised the issue in the boot2docker repo to see about getting
attention to it.

When time permits I was going to look deeper at it.

**Comment by AkihiroSuda** [comment]
This workaround should work:
```
$ wget http://tinycorelinux.net/6.x/x86_64/tcz/udev-extra.tcz
$ sudo tce-load -i udev-extra.tcz
$ sudo udevadm trigger
```

I also opened a pull req for adding `udev-extra` to default B2D distribution: boot2docker/boot2docker#1114

**Comment by byrnedo** [comment]
Sweet, will give this a try!

**Comment by clintonskitson** [comment]
Great work @AkihiroSuda!  I just tested this out and it works other than the `sudo tce-load -i udev-extra.tcz`.  I get an error saying don't run it as root.  Otherwise, it tested end-to-end perfectly.

```
curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -
```
```
rexray:
  storageDrivers:
  - virtualbox 
virtualbox:
  endpoint: http://10.0.2.3:18083
  volumePath: /Users/clintonkitson/VirtualBox Volumes/
  controllerName: SATA
```

```
root@default:/home/docker# rexray volume create --volumename=testing123 --size=1
name: testing123
volumeid: 2b242921-2536-44e6-971d-7540c290bd27
availabilityzone: ""
status: /Users/clintonkitson/VirtualBox Volumes/testing123
volumetype: ""
iops: 0
size: "1"
networkname: ""
attachments: []
```
```
root@default:/home/docker# rexray volume mount --volumename=testing123
/var/lib/rexray/volumes/testing123/data

root@default:/home/docker# rexray volume unmount --volumename=testing123
```

```
root@default:/home/docker# docker volume create --driver=rexray --name=testing234 --opt=size=2
testing234
root@default:/home/docker# docker run -ti --volume-driver=rexray -v testing234:/testing234 busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
c00ef186408b: Pull complete 
ac6a7980c6c2: Pull complete 
Digest: sha256:e4f93f6ed15a0cdd342f5aae387886fba0ab98af0a102da6276eaf24d6e6ade0
Status: Downloaded newer image for busybox:latest
/ # df /testing234
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/sdc               1998672      3076   1874356   0% /testing234
```

**Comment by clintonskitson** [comment]
@byrnedo Can you close this issue if you are satisfied?

**Comment by byrnedo** [comment]
Worked fine for me too, thanks for the help @clintonskitson , @AkihiroSuda
