### ISSUE TITLE
no storage drivers initialized on Ubuntu 14.04 

### ISSUE THREAD

**Issue by kyunam** [emccode/rexray#261]
Do I need to install something like ec2 driver (if so, how) ?

rexray:
    logLevel: debug
    osDrivers:
    - linux
    storageDrivers:
    - ec2
    volumeDrivers:
    - docker
aws:
    accessKey: ***
    secretKey: ***

parallels@ubuntu:~$ rexray volume get
DEBU[0000] updated log level                             logLevel=debug
INFO[0000] [linux]                                      
INFO[0000] [docker]                                     
INFO[0000] ec2                                          
DEBU[0000] core get drivers                              osDrivers=[linux] storageDrivers=[ec2] volumeDrivers=[docker]
INFO[0000] os driver initialized                         provider=linux
DEBU[0000] error initializing driver                     driverName=ec2 error.provider=ec2
INFO[0000] volume driver initialized                     provider=docker
Oops, an error occured!

  no storage drivers initialized

To correct the error please review:

  - Debug output by using the flag -l debug
  - The REX-ray website at https://github.com/emccode/rexray
  - The on↓ine he↓p be↓ow

Thanks,
Q

**Comment by clintonskitson** [comment]
Can you ensure that when you run "rexray env" that your aws credentials are
properly showing?

**Comment by kyunam** [comment]
yes. I see both accessKey & secretKey.

RACKSPACE_TENANTID=
GCE_KEYFILE=
VIRTUALBOX_PASSWORD=
REXRAY_LOGLEVEL=debug
OPENSTACK_USERID=
SCALEIO_USECERTS=false
REXRAY_VOLUME_MOUNT_PREEMPT=false
SCALEIO_SYSTEMNAME=
VIRTUALBOX_USERNAME=
OPENSTACK_REGIONNAME=
OPENSTACK_PASSWORD=
LINUX_VOLUME_ROOTPATH=/data
VIRTUALBOX_LOCALMACHINENAMEORID=
ISILON_VOLUMEPATH=
AWS_SECRETKEY=***
DOCKER_AVAILABILITYZONE=
OPENSTACK_AUTHURL=
RACKSPACE_PASSWORD=
AWS_REGION=
DOCKER_IOPS=0
XTREMIO_DEVICEMAPPER=false
REXRAY_STORAGEDRIVERS=ec2
ISILON_USERNAME=
VMAX_VMH_INSECURE=false
LINUX_VOLUME_FILEMODE=448
VIRTUALBOX_VOLUMEPATH=
RACKSPACE_USERNAME=
OPENSTACK_DOMAINID=
XTREMIO_MULTIPATH=false
XTREMIO_USERNAME=
SCALEIO_INSECURE=false
SCALEIO_USERID=
ISILON_NFSHOST=
VMAX_SID=
SCALEIO_ENDPOINT=
VMAX_INSECURE=false
SCALEIO_PROTECTIONDOMAINNAME=
VMAX_VOLUMEPREFIX=
RACKSPACE_AUTHURL=
ISILON_ENDPOINT=
VIRTUALBOX_CONTROLLERNAME=
VMAX_SMISPORT=
REXRAY_HOST=tcp://:7979
VIRTUALBOX_ENDPOINT=
OPENSTACK_TENANTNAME=
SCALEIO_PROTECTIONDOMAINID=
RACKSPACE_TENANTNAME=
VMAX_VMH_USERNAME=
RACKSPACE_DOMAINID=
REXRAY_VOLUMEDRIVERS=docker
SCALEIO_SYSTEMID=
XTREMIO_PASSWORD=
XTREMIO_ENDPOINT=
SCALEIO_STORAGEPOOLID=
VIRTUALBOX_TLS=false
OPENSTACK_AVAILABILITYZONENAME=
VMAX_PASSWORD=
ISILON_INSECURE=false
VMAX_VMH_PASSWORD=
XTREMIO_REMOTEMANAGEMENT=false
OPENSTACK_TENANTID=
OPENSTACK_USERNAME=
SCALEIO_PASSWORD=
XTREMIO_INSECURE=false
REXRAY_OSDRIVERS=linux
SCALEIO_STORAGEPOOLNAME=
AWS_ACCESSKEY=***
DOCKER_SIZE=0
VMAX_SMISHOST=
OPENSTACK_DOMAINNAME=
SCALEIO_USERNAME=
VMAX_VMH_HOST=
DOCKER_VOLUMETYPE=
RACKSPACE_USERID=
RACKSPACE_DOMAINNAME=
VMAX_USERNAME=
ISILON_PASSWORD=
VMAX_STORAGEGROUP=

**Comment by clintonskitson** [comment]
Is there a hypervisor running below this instance or is it an Ubuntu
instance on EC2?  Or better put what AMI did this instance come from?

**Comment by kyunam** [comment]
I'm running Ubuntu on Parallels on my Mac El Capitan.
I also tried to run directly on my Mac but I get "no OS driver initialized".

**Comment by clintonskitson** [comment]
Ahh.  So the EC2 driver is for instances running in AWS.  You can't
remotely use storage from Amazon unless your VM is running there.

If you want to run it from your Mac then you would use the VirtualBox
driver.

The following is a post describing this.

http://blog.emccode.com/2016/01/19/volume-plugins-with-docker-toolbox-and-boot2docker/

**Comment by kyunam** [comment]
ahh...thank you!

**Comment by akutz** [comment]
Hi @kyunam,

Closing this. Please feel free to re-open if you feel your question was not answered.

**Comment by vimalprakashts** [comment]
Hi , can you explain it more. I just want to know , how to connect to AWS EC2 instance.  I got My access key and secret. but dont know which instance it pick. or how to create instance and how to make to this ?
