### ISSUE TITLE
AWS Centos7.2 after reboot could not start

### ISSUE THREAD

**Issue by miry** [emccode/rexray#268]
I installed rexray on the Ec2 instance:

```
$ uname -a
Linux ip-10-0-8-100.ec2.internal 3.10.0-327.4.4.el7.x86_64 #1 SMP Tue Jan 5 16:07:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

after each reboot I see next in logs:

https://gist.github.com/miry/2905e9eac75f5f716c14

but it works if I run manually.

**Comment by clintonskitson** [comment]
Can you verify that "rexray env" returns the correctly configured
credentials for AWS?

It is best to run rexray interactively before trying to start it as a
service.

rexray volume -l debug

**Comment by miry** [comment]
@clintonskitson yes it works fine from the interactive. And service started correctly from the bash. I use `/etc/rexray/config.yml` to keep aws credentials.

**Comment by clintonskitson** [comment]
So this is the output when you run "rexray start -l debug"?

**Comment by clintonskitson** [comment]
@miry I do see your question for clearly now.  So during the init startup of REX-Ray on Centos 7.2, REX-Ray fails to start properly.  It is upon a manual start that it starts running.  I need to see about replicating this.

**Comment by miry** [comment]
I fixed the systemctl service:

```
[Unit]
Description=rexray
Before=docker.service

[Service]
Restart=always
RestartSec=30
EnvironmentFile=/etc/rexray/rexray.env
ExecStartPre=/usr/bin/rexray env
ExecStart=/usr/bin/rexray start -l debug -f
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process

[Install]
WantedBy=docker.service
```

**Comment by clintonskitson** [comment]
Thanks @miry!

Pulling the original file below.

```
[Unit]
Description=rexray
Before=docker.service

[Service]
EnvironmentFile={{.EnvFile}}
ExecStart={{.RexrayBin}} start -f
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process

[Install]
WantedBy=docker.service
```

Very interesting, sot he `ExecStartPre` looks to be your fix?  @akutz any ideas here?

**Comment by miry** [comment]
The fix is always restart. And I added interval 30 secs. So on boot I still has problem with loading driver, but at least the service tries to start again after 30 secs. and it success.

**Comment by clintonskitson** [comment]
@miry That makes more sense.  Different drivers may have dependencies on networking, etc to be functioning properly to be able to initialize.  Having this restart makes sense to overcome some of the unknown there in terms of dependencies not being ready.

**Comment by clintonskitson** [comment]
PR https://github.com/emccode/rexray/pull/272
