### ISSUE TITLE
Mount point for volumes conflicts with Docker local volumes

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#27]
/var/lib/docker/volumes/testa16

The volume mount point that is used should be outside of `/var/lib/docker/volumes` and likely associated to the volume manager.  Something like `/var/lib/rexray/volumes` would suffice.

https://github.com/docker/docker/issues/15880#issuecomment-135455678

**Comment by akutz** [comment]
Hi @clintonskitson,

I don't think I changed this code from the original, so it's likely what you had it. Are you asking me to change it because you want it relocated, or because you think I changed it from its original location? I only ask because I want to make sure that we have checks in place to ensure the suggested path exists.

**Comment by clintonskitson** [comment]
I will make the change here and add a PR.

**Comment by akutz** [comment]
Hi Clint,

Let me as I want to move the path to the config area. Unless you want to create a config variable with default options.

-- 
-a

"I wonder if procrastinators realize that they're not putting off work, just putting it off onto other people?"

**Comment by clintonskitson** [comment]
Nope, feel free.  If its a simple change to make it configurable, then I say go for it.  Otherwise, the only operational complexity I see with that is possibly having multiple RR instances running and the same volume trying to be mounted across the instances.  The first instance may allow it, but the second would atttempt it as well and likely fail.

I believe having a single path for both instances would be the best approach.  But I might differ from that if we said that all RR instances have the single path.

**Comment by clintonskitson** [comment]
Let me clarify..

1) Allow each RR instance to have its own mount path
2) Allow configurable mount path for all instances
3) Don't allow configurable mount path

I would be in for #2 or #3 right now.

**Comment by akutz** [comment]
Hi @clintonskitson,

Don't get me wrong, I think it should absolutely be a single path for all instances. I do believe however that that path should be configurable.

**Comment by clintonskitson** [comment]
Agree there

**Comment by akutz** [comment]
Yep, on same page.

**Comment by akutz** [comment]
Hi @clintonskitson,

We're going to have to do \#3 for now as there's no good way to restrict a config value once set to be used for all instances. I know how I *will* do it, but it will involve too much work for this release.
