### ISSUE TITLE
Dead link in the documentation

### ISSUE THREAD

**Issue by akamalov** [emccode/rexray#270]
There is a dead URL in: 

"To activate the ScaleIO driver please follow the instructions for activating storage drivers, using scaleio as the driver name."

https://github.com/emccode/rexray/blob/master/user-guide/config#activating-storage-drivers

Question: I am trying to activate scaleIO driver, how do I do that ?

**Comment by clintonskitson** [comment]
@akamalov The documentation is intended to be used from RTD, where this link is valid versus from the raw Github source.

http://rexray.readthedocs.org/en/stable/user-guide/storage-providers/scaleio/

Check the link above.

**Comment by clintonskitson** [comment]
@akamalov Can we close this issue and resolve in https://github.com/emccode/rexray/issues/271?

**Comment by akamalov** [comment]
Absolutely. Thanks!!!
