### ISSUE TITLE
scaleio driver: volume creation failes if mdm failed over

### ISSUE THREAD

**Issue by bottkars** [emccode/rexray#280]
same issue also with vipr: when mdm failed over, volume creation fails from rexray

**Comment by clintonskitson** [comment]
Not sure what the reference is to VIPR?  The volume creation from REX-Ray goes through the ScaleIO REST Gateway.  If it handles a failover of the MDM properly then we should also.

**Comment by bottkars** [comment]
Hi Clinton,issue is a mdm setup issue when Customer has not assigned all Management ips. Should ask The Rest api guys if we Need to rely on Management ip in mdm config when Provided The ips are Provided By Gateway servers

**Comment by clintonskitson** [comment]
Ok.  Please close issue if satisfied with response.  Thx
