### ISSUE TITLE
Incorrectly states status when process is not running with existing pid file

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#293]
If REX-Ray is killed with a `-9` the process stops but the `/var/run/rexray/rexray.pid`still exists.  This is expected behavior.  If you issue a `rexray service status` or do the same using a init service it incorrectly will still show REX-Ray as running.  I believe the behavior should be to perform the same logic as addressed in https://github.com/emccode/rexray/pull/262.

```
root@mesos-slave1:/home/vagrant# rexray start
Starting REX-Ray...SUCCESS!

  The REX-Ray daemon is now running at PID 1480. To
  shutdown the daemon execute the following command:

    sudo /usr/bin/rexray stop

root@mesos-slave1:/home/vagrant# kill -9 1480
root@mesos-slave1:/home/vagrant# rexray status
REX-Ray is running at pid 1480
root@mesos-slave1:/home/vagrant# rexray start
Starting REX-Ray...SUCCESS!

  The REX-Ray daemon is now running at PID 1495. To
  shutdown the daemon execute the following command:

    sudo /usr/bin/rexray stop

root@mesos-slave1:/home/vagrant# systemctl rexray status
```

**Comment by clintonskitson** [comment]
@akutz Can you look at this one for 0.3.2?

**Comment by akutz** [comment]
Hi @clintonskitson,

Sure thing. I agree that this should behave the way you described and that it's related to #262. Looks like I missed this. Well, it wasn't directly a part of the original issue, but certainly related.
