### ISSUE TITLE
Perform YAML validation of config files

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#294]
I have had YAML formatting problems numerous times that resulted in the storage driver not starting correctly.  Troubleshooting was able to narrow it down to invalid characters etc in the YAML files.

It would help the user experience a lot when configuring new and more complex drivers to perform a basic validation of the config.yml file prior to attempting a service start with it.

**Comment by akutz** [comment]
Hi @clintonskitson,

I agree this is a good idea, and I've even looked into it in the past, but Viper has always failed gracefully, ignoring bad content, when loading files. To that end I've just submitted a [PR to Gofig](https://github.com/akutz/gofig/pull/6) that can be used to validate YAML. See the test [TestValidateYAML](https://github.com/akutz/gofig/blob/master/gofig_test.go#L137).

**Comment by clintonskitson** [comment]
Very nice @akutz.  I just did some basic testing with it and it is going to help a lot.  The package looks to be pretty verbose with errors.  Maybe we should add in a brief blurb into the docs in the configuration section about taking the config to yamllint.com if there are errors in their configs.

```
 line 4: found a tab character that violate indentation
```

**Comment by akutz** [comment]
Hi @clintonskitson,

Well, I'm not controlling content of said errors. To what type of verbosity are you referring? Also, I had no intention of necessarily printing out the direct errors. We could always catch the error and print out to the user that they should take the YAML and submit it to yamllint.com themselves. We can't expect to have network access to do it programmatically, but we can let them know to do it on error.

**Comment by clintonskitson** [comment]
Yah exactly.  I was actually just thinking about calling it out with a couple of sentences in the docs themselves.  But an explicit comment to verify it online or with a lint would work as well.

What would be your concern with repeating the errors that YAML returns?

**Comment by akutz** [comment]
I have no such concern; from your comments above it seemed you did regarding the errors' verbosity.

**Comment by clintonskitson** [comment]
Nope, I believe they would be very helpful for people configuring the service.

**Comment by akutz** [comment]
> The package looks to be pretty verbose with errors. Maybe we should add 

The declaration of verbosity followed by a recommendation seems to me to indicate "Because it does this, we should do that as a counter/enhancement."

Just a case of intent and tone lost in text communication :)

**Comment by clintonskitson** [comment]
Yeah, I missed the "I like this" part. =)

**Comment by clintonskitson** [comment]
@akutz Is this something we are comfortable with introducing into 0.3.2?
