### ISSUE TITLE
Reporting module name in log

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#295]
With the introduction of the modules, it has introduced a necessary context that should be tracked in the logs.  Right now, when requests come in you can't differentiate with module or storage provider is responding to the request.

This log was generated from a single `docker` instance talking with three volume endpoints that are all pointing to the same storage platform.

I believe this is part of some of the 0.4 changes that @akutz has planned re context, but wanted to make sure we track it.

```
time="2016-02-12T15:50:26Z" level=info msg="getting volume" driverName=docker volumeName=newvol2001 
time="2016-02-12T15:50:26Z" level=info msg="getting volume" driverName=docker volumeName=newvol2001 
time="2016-02-12T15:50:32Z" level=info msg="getting volume" driverName=docker volumeName=newvol2001
```

**Comment by akutz** [comment]
Hi @clintonskitson,

I opened a PR where I implemented a short-term fix for this.

**Comment by clintonskitson** [comment]
https://github.com/emccode/rexray/pull/296
