### ISSUE TITLE
Unable to build using the Docker method

### ISSUE THREAD

**Issue by sayash** [emccode/rexray#297]
Trying to build rexray from source using the Docker method with the following commands:

```bash
SRC=$(mktemp -d 2> /dev/null || mktemp -d -t rexray 2> /dev/null) 
cd $SRC \
  && docker run --rm -it \
    -v $SRC:/usr/src/rexray \
    -w /usr/src/rexray \
    golang:1.5.1 \
    bash -c "git clone https://github.com/emccode/rexray.git . && make build-all"
```
Make fails with the errors as shown here at [pastebin](http://pastebin.com/raw/GVp7CUCa)

Maybe head isn't in a build-able state?

**Comment by akutz** [comment]
Hmmm, try:

```
SRC=$(mktemp -d 2> /dev/null || mktemp -d -t rexray 2> /dev/null) 
cd $SRC \
  && docker run --rm -it \
    -v $SRC:/usr/src/rexray \
    -w /usr/src/rexray \
    golang:1.5.1 \
    bash -c "git clone https://github.com/emccode/rexray.git . && env GO15VENDOREXPERIMENT =1 make build-all"
```

I think [this line](https://github.com/emccode/rexray/blob/master/Makefile#L20) should be changed to `export GO15VENDOREXPERIMENT=1`. It's a small, but subtle difference that might determine if the variable actually gets exported from Make's environment.

**Comment by clintonskitson** [comment]
Going to work on the PR to capture this @akutz and the details around ensuring that REX-Ray is in the $GOPATH/src/github.com/emccode

**Comment by clintonskitson** [comment]
@sayash Can you close the issue if you are satisfied?

**Comment by sayash** [comment]
Thanks!
