### ISSUE TITLE
download_rexraycli

### ISSUE THREAD

**Issue by ariksa** [emccode/rexray#31]
The download_rexraycli link is "https://github.com/emccode/rexray/releases/download/latest/rexray-Linux-x86_64", while it seems that this url doesn't exist.
I changed it manually to "https://github.com/emccode/rexray/releases/download/v0.1.150418/rexray-Linux-x86_64"

**Comment by clintonskitson** [comment]
Thanks for noticing this.  I have updated the latest tag with v0.1.150720.

**Comment by ariksa** [comment]
Thanks.
Please note that it should be probably updated in other projects. For example I hit it again in "vagrant-puppet-scaleio"
