### ISSUE TITLE
Docker fails to run container with "No volumes returned by name"

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#315]
With Docker 1.10 & REX-Ray 0.3.2 this issue is not valid.

There was previously an issue where Docker would maintain the state of volumes that it had been associated with prior. This means that if you do a `docker run` with volumes, then any proceeding `docker volume ls` would result in seeing any previous volumes.

The problem is that the list may be out of sync with the backend storage platform. If a delete occurs directly from REX-Ray or directly from the storage platform, the volume name would be unable to be reused until Docker's state for the volume had been cleared and previous containers using the volumes were deleted. This is the case since a `Path()` operation from Docker would occur for that volume name, and RR would return an error because the volume name didn't exist.

In Docker 1.10 and REX-Ray 0.3.2, the `docker volume ls` results in only information coming from REX-Ray. Docker no longer maintains the state about volumes and names of volumes so RR and the storage platforms are authoritative.

```
time="2016-02-24T15:31:02Z" level=error msg="/VolumeDriver.Path: error returning path" error="No volumes returned by name" 
time="2016-02-24T15:31:02Z" level=error msg="No volumes returned by name" 
```

**Comment by clubanderson** [comment]
Clinton, I just got this error today.  What can I do to remove this caching?  

Docker version 1.10.3, build 20f81dd

docker volume ls
DRIVER              VOLUME NAME

rexray log:
Apr 14 16:33:52 css-c-sdlc-021.cisco.com rexray[5153]: time="2016-04-14T16:33:52Z" level=error msg="/VolumeDriver.Path: error returning path" error="No volumes returned by name"
Apr 14 16:33:52 css-c-sdlc-021.cisco.com rexray[5153]: time="2016-04-14T16:33:52Z" level=error msg="No volumes returned by name"

is mesos or marathon hanging onto something?  All my docker containers are managed by marathon and mesos.  But I am using the rexray docker volume driver.

**Comment by clubanderson** [comment]
please re-open #315 @clintonskitson

**Comment by clintonskitson** [comment]
Are you configuring rexray using module configuration? What does the config look like?

What does a `rexray volume ls` look like?

**Comment by clubanderson** [comment]
Empty return. No errors though. Scaleio log shows successful rc

**Comment by clintonskitson** [comment]
Can you create a volume and then do a ls? I am assuming you are targeting a certain storagePool with your config right now that has no volumes in it?

**Comment by clubanderson** [comment]
Yes. I have done that also. Works fine. And I can then list it

**Comment by clintonskitson** [comment]
So a `rexray volume ls` works, rexray is started with `rexray start`, but a `docker volume ls` does not list any volumes at that point?

**Comment by clubanderson** [comment]
[root@css-c-sdlc-021 ~]# rexray volume create --volumename="test" --size=1
name: test
volumeid: fb38068c00000000
availabilityzone: protection_domain1
status: ""
volumetype: pool1
iops: 0
size: "8"
networkname: ""
attachments: []

[root@css-c-sdlc-021 ~]# docker volume ls
DRIVER              VOLUME NAME
rexray              test

[root@css-c-sdlc-021 ~]# rexray volume ls
- name: test
  volumeid: fb38068c00000000
  availabilityzone: protection_domain1
  status: ""
  volumetype: pool1
  iops: 0
  size: "8"
  networkname: ""
  attachments: []

**Comment by clubanderson** [comment]
the problem is that marathon son has 3 volumes in it (docker parameters), they don't exist (they did in an old install).  Where is it being cached that the volumes are already created and do not need to be created from scratch?

**Comment by clintonskitson** [comment]
@clubanderson Can you describe the situation again, I am not following. What you just showed looks to be accurate to me.

**Comment by clubanderson** [comment]
[root@css-c-sdlc-021 ~]# rexray volume create --volumename="test" --size=1
name: test
volumeid: fb38068c00000000
availabilityzone: protection_domain1
status: ""
volumetype: pool1
iops: 0
size: "8"
networkname: ""
attachments: []

[root@css-c-sdlc-021 ~]# docker volume ls
DRIVER              VOLUME NAME
rexray              test
[root@css-c-sdlc-021 ~]# rexray volume ls
- name: test
  volumeid: fb38068c00000000
  availabilityzone: protection_domain1
  status: ""
  volumetype: pool1
  iops: 0
  size: "8"
  networkname: ""
  attachments: []

[root@css-c-sdlc-021 ~]# cd
[root@css-c-sdlc-021 ~]# ls
artifactory  EMC  panteras-both
[root@css-c-sdlc-021 ~]# cd artifactory/
[root@css-c-sdlc-021 artifactory]# LS
-bash: LS: command not found
[root@css-c-sdlc-021 artifactory]# ls
run
[root@css-c-sdlc-021 artifactory]# cd run
[root@css-c-sdlc-021 run]# ls
service.json
[root@css-c-sdlc-021 run]# more service.json 
{  
   "id":"artifactory",
   "cpus":1.0,
   "mem":4096.0,
   "instances":1,
   "constraints": [["hostname", "CLUSTER", "css-c-sdlc-021.cisco.com"]],
   "env":{  
      "HAPROXY_ADD_DOMAIN":".css-c-sdlc-021.cisco.com",
      "SERVICE_TAGS":"haproxy,urlprefix=artifactory.develop-4",
      "SERVICE_NAME":"artifactory",
      "SERVICE_8000_CHECK_HTTP":"/artifactory"
   },
   "container":{  
      "type":"DOCKER",
            "docker":{  
         "image":"css-c-sdlc-021.cisco.com:5000/artifactory:0.1.0",
         "privileged":true,
         "forcePullImage":false,
         "network":"BRIDGE",
         "portMappings": [
            { 
               "containerPort": 8081,
               "hostPort": 8000,
               "protocol": "tcp" 
            }
         ],
         "parameters": [
            { "key": "volume-driver", "value": "rexray" },
            { "key": "volume", "value": "artifactory-data:/var/opt/jfrog/artifactory/data" },
            { "key": "volume", "value": "artifactory-logs:/var/opt/jfrog/artifactory/logs" },
            { "key": "volume", "value": "artifactory-backup:/var/opt/jfrog/artifactory/backup" },
            { "key": "volume", "value": "artifactory-etc:/var/opt/jfrog/artifactory/data/etc" }
         ]      }
   },

It appears that mesos is not trying to "create" the volumes.  It is looking for the volumes to already be there.  When marathon,mesos, docker, scaleio, rexray are installed fresh, this isn't an issue.  The problem right now, I took down scaleio and then built it again.  Destroying and re-creating the marathon job for artifactory should realize this and create the volumes again.  It is not doing that.  It expects that scaleio came back with volumes intact even though the container is brand new.  Where is this being cached?  Marathon, mesos?

**Comment by clintonskitson** [comment]
Have you tried a "rexray restart"? There is a level of cache in place that
can be disabled if it is causing problems.

**Comment by clubanderson** [comment]
I've tried restarting the service. Did not help

**Comment by clintonskitson** [comment]
It quite possibly could be from an old container that is mapping these. Can you try removing the containers that are on the system or stopped? This could be causing docker to maintain the volume awareness.

**Comment by clubanderson** [comment]
So, what appears to have been happening is that each time a mesos failure occurred (couldn't map a drive) a retry was launched by marathon.  This leaves X number of dead/exited containers lying around the docker ecosystem.  To fix this issue, before I spawn a new version of a container, I cleanup the exited ones...

docker rm $(docker ps -aq)

that then allows me to 

docker volume rm $(docker volume ls)

of course I filter this to only give me the items that pertain to the service I am using.

Problem solved.

**Comment by clubanderson** [comment]
I need to try to kill scaleio and then see what happens to the volumes.  Thats the next test.
