### ISSUE TITLE
Fails to start as service using modules and one default module config

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#316]
In testing the 0.3.2-RC3 I ran into an issue relating to the compatibility of the module based configuration if only specifying a single module. A failed start would result from this.

@akutz Is this expected behavior?

```
DEBU[0000] error initializing driver                     driverName=ScaleIO error.insecure=false error.useCerts=false error.provider=ScaleIO error.moduleName=default-docker error.endpoint=
INFO[0000] os driver initialized                         moduleName=default-docker provider=linux
INFO[0000] docker volume driver initialized              availabilityZone= iops= moduleName=default-docker provider=docker size= volumeRootPath=/data volumeType=
DEBU[0000] checking volume path cache setting            pathCache=true
INFO[0000] vdm.List                                      driverName=docker moduleName=default-docker
INFO[0000] listing volumes                               driverName=docker moduleName=default-docker
ERRO[0000] default module(s) failed to start            
INFO[0000] service sent registered modules start signals 
ERRO[0000] service initialized failed                   
INFO[0000] error initializing drivers  
```

This configuration does not work for a single module. I previously had two defined, and just removed one for ancillary testing purposes. But I could see this situation occurring.

```
rexray:
  logLevel: debug
  storageDrivers:
  - scaleio
  modules:
    default-docker:
      type: docker
      desc: The default docker module.
      host: unix:///run/docker/plugins/scaleio1.sock
      spec: /etc/docker/plugins/scaleio1.spec
      scaleio:
        endpoint: https://192.168.50.12:443/api
        insecure: true
        userName: admin
        password: XScaleio123
        systemId: 0651e26c792a7a47 
        protectionDomainName: pdomain 
        storagePoolName: pool1
```

This configuration works for a single module.
```
rexray:
  storageDrivers:
  - scaleio
  logLevel: debug
scaleio:
  endpoint: https://192.168.50.12:443/api
  insecure: true
  userName: admin
  password: XScaleio123
  systemId: 0651e26c792a7a47
  protectionDomainName: pdomain
  storagePoolName: pool1
```

**Comment by akutz** [comment]
Hi @clintonskitson,

Have you tried it while reverting the cached paths commit? It sounds as if not enough testing was done with the cached paths in conjunction with the modular configuration support. Also, please start specifying the configurations the way I've previously stated they should be specified. Ex:

```
rexray:
  logLevel: debug
  storageDrivers:
  - scaleio
  modules:
    default-docker:
      host: unix:///run/docker/plugins/scaleio1.sock
      spec: /etc/docker/plugins/scaleio1.spec
scaleio:
    endpoint: https://192.168.50.12:443/api
    insecure: true
    userName: admin
    password: XScaleio123
    systemId: 0651e26c792a7a47 
    protectionDomainName: pdomain 
    storagePoolName: pool1
```

We need a baseline. Once the baseline is established, then you are free to define things in a non-standard manner.

**Comment by clintonskitson** [comment]
@akutz My example is referencing our first example in the documentation, but pulled back to one module.

I did test your version and it does work that way.

**Comment by akutz** [comment]
Hi @clintonskitson,

I know why it's failing. And it's the cached commit. It is because copying a config instance doesn't retain the scope of the original instance. For a test, **before** [line 64 of voldriver.go](https://github.com/emccode/rexray/blob/master/daemon/module/docker/volumedriver/voldriver.go#L64) add the code:

```
cc = cc.Scope("rexray.modules.default-docker")
```

That's just to prove my theory. If that works I'll update Gofig with the patch that retains the Scope with a copy.

**Comment by akutz** [comment]
Yes, but that was *your* example for which I was not in favor. The second example in the documentation is the one I prefer and communicate to others. However, despite my issues with the one you continue to elect to use, it *should* work. Please see my above comment as to why it is likely failing.

**Comment by clintonskitson** [comment]
@akutz Roger that, it works.

**Comment by akutz** [comment]
Hi @clintonskitson,

It should work now without any chance to REX-Ray since it pulls master for gofig, and I just [accepted the PR for that](https://github.com/akutz/gofig/pull/7) that fixes the issue. Simply ensure that gofig is up to date by nuking your vendor dir and doing a `go get -u github.com/akutz/gofig`.

Once proven, please close this issue.

**Comment by clintonskitson** [comment]
Thanks @akutz

**Comment by akutz** [comment]
Yup. You're welcome. Glad it was an easy one :)

-- 
-a
