### ISSUE TITLE
Malformed host header reported from Docker

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#317]
The 0.3.2-RC3 release was built using Go 1.6. If using this in combination with Docker 1.9 or before, it may result in the following error. Docker 1.10 looks to not be impacted with this problem.

```
Error response from daemon: Error looking up volume plugin rexray: Plugin Error: Plugin.Activate, 400 Bad Request: malformed Host header
```

@akutz It looks like Go 1.6 is enforcing a new Host header requirement. See conversation here https://groups.google.com/forum/#!topic/golang-codereviews/CPeFXzMJRzI

If we are going to compile against Go 1.6, then let's see about modifying our behavior to ensure that requests that do not specify a Host still work as expected.

Manually issuing requests to rexray-0.3.2-RC3 does not work.
```
echo -e "POST /Plugin.Activate HTTP/1.1\r\n" | socat unix-connect:/run/docker/plugins/rexray.sock STDIO
HTTP/1.1 400 Bad Request
Content-Type: text/plain
Connection: close

400 Bad Request: missing required Host header
```

Manually issuing requests to rexray-0.3.2-RC2 works.
```
echo -e "POST /Plugin.Activate HTTP/1.1\r\n" | socat unix-connect:/run/docker/plugins/rexray.sock STDIO
HTTP/1.1 200 OK
Content-Type: application/vnd.docker.plugins.v1.2+json
Date: Wed, 24 Feb 2016 22:41:01 GMT
Content-Length: 33

{"Implements": ["VolumeDriver"]}
```

**Comment by akutz** [comment]
Hi @clintonskitson,

As this release includes patches specifically for Docker 1.10, REX-Ray 0.3.2 should raise the minimum requirement for Docker to 1.10 and require the host header. I don't care about manual invocations against the module -- people can adjust their calls to include a valid Host header. The [Host header is a required part of the HTTP 1.1 specification](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html), and we're not going to be backwards compatible with invalid use cases. This issue will be documented as "Won't Fix" as it is simply a case where Golang has updated its server code to HTTP 1.1 spec-compliant.

**Comment by clintonskitson** [comment]
@akutz The functionality addressed here does account for Docker 1.10 enhancements, but it is still backward compatible with previous versions. I don't see a need to instantiate a compatibility matrix at this point.

**Comment by clintonskitson** [comment]
Fix here for now could be to revert to Go 1.5x for 0.3 and make that choice explicitly for the 0.4 releases.

**Comment by akutz** [comment]
Hi @clintonskitson,

This is an issue of previous versions of Golang not being compliant with the HTTP 1.1 specification. Golang 1.6 *is* compliant. I closed this issue because we're not going to subvert a language's adherence to the HTTP, or any other, specification. It would be like bypassing some aspect of TLS because it's inconvenient. What is your suggestion?

1. Restrict REX-Ray to Golang 1.5 until such time that Docker and all other consumers of REX-Ray is X number of versions of Go ahead of 1.5?
2. Copy and then keep up-to-date the source for the Golang stdlib HTTP server so we can provide a version of that with the HTTP/1.1 specification required HOST header removed?

I dislike both of the above issues, and my decision is to enforce the HOST header.

**Comment by akutz** [comment]
Hi @clintonskitson,

There is no reason that the requirement cannot be made explicit for this release. Again, this is a requirement of the HTTP specification to which Go merely caught up.

**Comment by clintonskitson** [comment]
@akutz What is our benefit to enforcing the Header considering the state of the eco-system?

**Comment by akutz** [comment]
Hi @clintonskitson,

1. Accurate logging
2. Accurate auditing
3. Handling reverse-proxy scenarios (not possible without the Host header set)
4. Multiple server-side end-points

**Comment by clintonskitson** [comment]
@akutz We are talking about communication that occurs over a local socket file for 0.3.2.

**Comment by akutz** [comment]
Hi @clintonskitson,

That's the default configuration, but nothing restricts it to that. A user could configure it differently.

**Comment by clintonskitson** [comment]
@akutz The volume driver interface is not useful in a remote fashion today. I am going to repeat, there is no benefit today for enforcing a Header and Go 1.6 and its impact was not a properly planned change.

**Comment by akutz** [comment]
>  was not a properly planned change

Actually, this is an inaccurate statement. I researched the aspects of 1.6, and I was actually aware of the changes with the HTTP library, and they were in fact my primary impetus for making the change. I was performing perf tests with 1.6 RCs to see where the inclusion of HTTP/1.2  enhanced even local performance as well as how it would impact future inclusion of the TLS overhead. 

I'll repeat, I have no problem excluding the manual invocations of curl with this change -- these are not valid or supported use cases and exist only for people debugging or testing the product. Consumers can *easily* add a host header to these calls. If that is the only reason for reverting to 1.5, then I'll re-close this ticket.

However, if it's truly not present in versions of Docker prior to 1.10, then we should consider reverting to Golang 1.5 for the time being as Docker 1.10 has only been available for 20 days as of today. However, I'm not certain this is the case (the absent Host header). Cursory research shows that Docker 1.9 does in fact send the host header properly, so I'm not sure why other tests show it does not.

Can you please provide a simple and straight-forward example to show how Docker 1.9 fails to provide the Host header?

**Comment by akutz** [comment]
Closed with 0.3.2-RC4

**Comment by clintonskitson** [comment]
@akutz It is Docker making calls to us, it is not configurable.

**Comment by akutz** [comment]
FYI - Docker is tracking this at https://github.com/docker/docker/issues/20865

**Comment by dtx** [comment]
Just hit this myself. Working around compiling 0.3.3 with go1.5 to see if that works. Will update this thread for future folks.

**Comment by clintonskitson** [comment]
That will work. Rex 0.4 is compatible with Docker 1.10+ because of this.

**Comment by clintonskitson** [comment]
You can download the pre built binaries instead of compiling as well.

**Comment by dtx** [comment]
it worked well. Here is the dockerfile I used to build with go1.5. as @clintonskitson mentioned, you are better off using your pre-built binaries, but if you have a bunch of business-specific changes in your fork then you might have to run your own build. Here is what I did.

```
FROM ubuntu:14.04

 ENV GOVERSION 1.5

 RUN apt-get update -y && apt-get install --no-install-recommends -y -q \
     build-essential \
     ca-certificates \
     curl

 RUN mkdir /goroot && \
     mkdir /gopath && \
     curl https://storage.googleapis.com/golang/go${GOVERSION}.linux-amd64.tar.gz | \
          tar xzf - -C /goroot --strip-components=1

 ENV CGO_ENABLED 0
 ENV GOPATH /gopath
 ENV GOROOT /goroot
 ENV PATH $GOROOT/bin:$GOPATH/bin:$PATH

 RUN mkdir -p $GOPATH/src/github.com/emccode/rexray
 WORKDIR $GOPATH/src/github.com/emccode/rexray


 CMD make
```
Then I did:
```
docker build -t rexray -f Dockerfile .
export CURDIR=$(pwd)
docker run --rm -it -v $CURDIR:/gopath/src/github.com/emccode/rexray --name rexray rexray bash

```
Inside the container, run the make and copy the binary to the mount path after it succeeds:
```
root@996dc3046eda:/gopath/src/github.com/emccode/rexray# make
root@996dc3046eda:/gopath/src/github.com/emccode/rexray# cp /gopath/bin/rexray ./
root@996dc3046eda:/gopath/src/github.com/emccode/rexray# exit
```

You should now have your binary in your mount path on your host.
