### ISSUE TITLE
Add commit number to 'rexray version'

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#32]
Would be nice to directly correlate a commit hash to a binary even with actual releases.  Having `rexray version` return version and commit for all releases would help here.

**Comment by akutz** [comment]
I will be opening a pull request to close this issue.

![image](https://cloud.githubusercontent.com/assets/101085/9803822/97e69cf0-57ec-11e5-9b85-8f8003983052.png)

**Comment by akutz** [comment]
Closed with PR #37

**Comment by clintonskitson** [comment]
Ping @akutz.. In the future I wonder if it is possible to check for uncommitted changes and signify dirty possibly?

**Comment by akutz** [comment]
That's definitely possible, and not that difficult to do. By the way, "Formed" is the build date, not the commit date, so that will help too as it reflects when it was built.
