### ISSUE TITLE
RexRay cannot initiate storage driver with new ScaleIO 2.0 

### ISSUE THREAD

**Issue by docdentz** [emccode/rexray#333]
Hi All,

Unfortunately after upgrading my cluster to ScaleIO 2.0 I am not able to get rexray to work anymore. 
Attached is the Debug message:
INFO[0000] volume driver initialized                     provider=docker
DEBU[0000] error initializing driver                     driverName=ScaleIO error.insecure=true error.useCerts=false error.userName=admin error.password="******" error.provider=ScaleIO error.endpoint="https://192.168.1.10/api"

br,

Daniel

**Comment by clintonskitson** [comment]
ScaleIO v2 has not been tested w REX-Ray as of yet. Support will come after
0.3.2.

**Comment by clubanderson** [comment]
I need this support as well.  I can't find scaleio v1.3 - do you have a link to it?  I am stuck!!!

**Comment by clintonskitson** [comment]
We actually do.

https://github.com/emccode/vagrant/commit/de994cf7777606c6c50daaefc1b2c936295247e1

This commit has the old download location and the new one. There old one
should be able to be used while filling in 1 for version_major.

**Comment by clubanderson** [comment]
I took a look for http://downloads.emc.com/emc-com/usa/ScaleIO/ScaleIO_Linux_v1.32.zip.  Not there - 404.  I also tried to clone the multi-env commit and then do a make.  Dependencies on github.com/rackspace/gophercloud/openstack/blockstorage/v2/extensions/volumeactions.  I can't compile the source.  I must be doing something wrong.  Please help me understand how to compile.  I tried on Mac OS and RHEL7.1.

**Comment by clubanderson** [comment]
I forked #350 and got
drivers/storage/scaleio/scaleio.go:82: too many values in struct initializer

build won't succeed - any ideas?

**Comment by clubanderson** [comment]
in order for #350 to compile you need to update the struct for configconnect in api.go (src/github.com/emccode/goscaleio/api.go)

type ConfigConnect struct {
	Endpoint string
	Username string
	Password string
}

its missing the new "version" string from drivers/storage/scaleio/scaleio.go

**Comment by clubanderson** [comment]
forked goscaleio... changed the configconnect struct to have version.  changed import in the fork for #350 to pull from my fork for scaleio.  The build for rexray finishes.  I install the rexray driver and then attempt a service rexray start.  I get 

Binary: /usr/bin/rexray
SemVer: 0.3.2
OsArch: Linux-x86_64
Branch: v0.3.2
Commit: 806dc9be95ad20cfbaeb52869f500047278f52a6
Formed: Fri, 04 Mar 2016 22:58:00 UTC

time="2016-04-06T20:25:22Z" level=error msg="default module(s) failed to start" 
time="2016-04-06T20:25:22Z" level=error msg="service initialized failed" 

i don't get any more info than this

**Comment by clintonskitson** [comment]
@clubanderson Pointed you there before I had the chance to test it. If it is complaining about the dependencies then it is likely the dependencies in the glide file that are not being pulled down or not correct.

https://github.com/emccode/goscaleio/pull/10

See the above commit which is the update to the scaleio bindings that include v2. You should be able to edit the glide.yaml file and update the commit id and github location to this branch. Following that clear out your vendor directory and re-run the make.

**Comment by clubanderson** [comment]
@clintonskitson - thank you so much for the help.  I forked the rexray and go scaleio projects and then played with travis to see how to compile myself.  My go path was the issue.  I was able to clone the fixes in both repos to my laptop, build and now use the binary.  

After compiling the binary I need to know the best way to register it as a service.  Any hints?  I can issue "rexray service start", but I would like to do "service rexray start" instead so that I can put this into chkconfig.  Thank you

**Comment by clintonskitson** [comment]
"rexray install" does this for you. So first step is to put RR binary where
you want it, then run that command. Any commands following like "rexray
start" will leverage init system to spawn.

**Comment by akutz** [comment]
Closed with #355

**Comment by clubanderson** [comment]
I was able to build the RPM finally.  I was missing rpm-build on my build environment.  It is installing properly now.

**Comment by akutz** [comment]
Hi @clubanderson,

I should be more specific [here](http://rexray.readthedocs.org/en/stable/dev-guide/build-reference/#build-rpms) when calling out what the RPM environment means. If you'd like to file a ticket to track the issue, I'll make sure to add additional information about requiring `rpm-build` as well as other tools.

**Comment by akutz** [comment]
Hi @clubanderson,

By the way, the RPM and DEB are always built for the latest build and copied into the latest folder for that build's files. Go [here](https://bintray.com/emccode/rexray/staged/0.3.3-rc1/view#files/staged/latest) and click on the `Files` tab followed by the `latest` folder to find the RPM for 0.3.3-rc1.
