### ISSUE TITLE
Documentation for Kubernetes use

### ISSUE THREAD

**Issue by rimusz** [emccode/rexray#344]
documentation update for Kubernetes use

**Comment by clintonskitson** [comment]
@rimusz Thanks for the comment here. We will definitely post changes for the 0.4 release where we formally introduce k8 support.

**Comment by rimusz** [comment]
@clintonskitson can the rexray be used with kubernetes v1.2?

**Comment by clintonskitson** [comment]
@rimusz We did a build of integrating RR 0.3 against K8 1.20-alpha8 and documented how to use it in this blog post.

http://blog.emccode.com/2016/03/03/docker-toolbox-with-kubernetes-rex-ray-and-persistent-volumes/

The changes can be applied to later k8 branches pretty easily. It is done via a branch [here](https://github.com/clintonskitson/kubernetes/tree/feature/rexray). 

We are waiting on doing a formal PR into k8 for REX-Ray 0.4. In this version we introduce a client/server model via [libStorage](https://github.com/emccode/libstorage). Today the kubelet process is build to include all of RR, which doesn't make sense. In .next, it will only include the lightweight client which really represents a remotable and portable volume plugin architecture for multiple container platforms.

**Comment by rimusz** [comment]
@clintonskitson thanks for the update, I was hoping it is already merged to k8s v1.2 :)

**Comment by clintonskitson** [comment]
Closing this for now as it will be introduced via the github.com/emccode/libstorage project instead. @vladimirvivien
