### ISSUE TITLE
The systemd config broken in 0.2.0-rc2

### ISSUE THREAD

**Issue by Arkan** [emccode/rexray#36]
With all the changes, the systemd configuration is broken, and used the last daemon argument.

It seems to be fixed with `ExecStart=/opt/rexray/rexray start --foreground=true` though.

**Comment by akutz** [comment]
Hi @Arkan,

Thank you for the e-mail and submitting this to the Issue tracker as I asked. May I have a look at your `REX-Ray` service unit file please?

**Comment by akutz** [comment]
Hi @Arkan, 

I tested the fix, merged #42, and you should be good to go.
