### ISSUE TITLE
Feature to disable volume removal 

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#360]
It was recently determined that a combination of features in Mesos when using the Docker containerizer against Docker version below 1.10 could result in unplanned volume removal. More details to come.

An easy safety net would be to allow the silent ignore feature for volume removal requests. This way any attempt to remove by Docker would be ignored by REX-Ray. This could be implemented at a module level giving control over which volume drivers can be users with full privilege on the same RR instance.

**Comment by akutz** [comment]
Good idea. I don't mean to pick nits, but it wouldn't be at the module level. It would be at the volume/integration driver level and like any config option, you can use modules to create scoped config views.

**Comment by clintonskitson** [comment]
https://github.com/emccode/rexray/pull/366
