### ISSUE TITLE
Option to mount one specific dir or file from one volume

### ISSUE THREAD

**Issue by gonzalomarcote** [emccode/rexray#362]
Hi,

I am using rexray with the openstack driver.
I want to launch one MySQL container in a docker swarm cluster like this:
`docker -H tcp://X.X.X.X:3376  --name db01 --net=internal --volume-driver=rexray -v db01/my.cnf:/etc/mysql/my.cnf -v db01/mariadb:/var/lib/mysql -v db01/certs/:/etc/ssl/mysql:ro -d mysql:latest`

I have tried this, but the problem I face with rexray is that I can not specify one dir or file to mount from the volume.
The only option is to create one volume for each mount point, even one of the minimum (1GB) for one simple file like my.cnf, like this:
`docker -H tcp://X.X.X.X:3376  --name db01 --net=internal --volume-driver=rexray --volume-driver=rexray -v db01-mysql:/etc/mysql -v db01-mariadb:/var/lib/mysql -v db01-certs/:/etc/ssl/mysql:ro -d mysql:latest`

I would like to have only one volume "db01" with file my.cnf and "mariadb" and "certs" dirs, and not to be creating one volume for each one.
Is this option possible?. If not contemplated, it definitely would be useful...

**Comment by clintonskitson** [comment]
Gonzalo,

That is actually a limitation of Docker today in terms of not allowing you
to mount files from an external volume. A formal request would need to be
made w Docker to enable that.

One option you have is to create the volume ahead of time at whatever size
you would like using the typical tools. The size won't interfere with RR
using the volume.

**Comment by gonzalomarcote** [comment]
Thank you for the clarification.
To create a smaller volume with cinder (openstack) is a valid option for me.

**Comment by clintonskitson** [comment]
@gonzalomarcote If you're satisfied with the response, please close the issue.

**Comment by gonzalomarcote** [comment]
Sure.
I will open one request to the docker team for them to work on that limitation.
