### ISSUE TITLE
Fix dead links in docs

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#369]
Adding placeholder to check docs for dead links. Storage drivers table does incorrectly reference drivers today.

**Comment by akutz** [comment]
Hi @clintonskitson,

Please provide examples. I've fixed some before, and they technically weren't broken as they were being visited from the wrong location (inside Github). I just want to make sure we record the specific links and times (and commits) at which they were reported. Thanks!

**Comment by clintonskitson** [comment]
All of the storage platform links from the main page look to be broken in the table.

http://rexray.readthedocs.org/en/stable/user-guide/storage-providers/scaleio

**Comment by clintonskitson** [comment]
addressed in here https://github.com/emccode/rexray/pull/337
