### ISSUE TITLE
Question: Do I have to use AWS EC2 in case if I use a driver as REX-Ray?

### ISSUE THREAD

**Issue by NetworkZIGI** [emccode/rexray#391]
Do I have to use AWS EC2 in case if I use a driver as REX-Ray?

**Comment by kacole2** [comment]
@NetworkZIGI no, AWS is not a hard requirement. REX-Ray supports the following storage platforms:
Amazon EC2 (EBS), Google Compute Engine (Disk), Open Stack (Cinder), Rackspace (Cinder), EMC (ScaleIO, XtremIO, VMAX, Isilon), and Virtual Box (Virtual Media).

You can read about each of them and how to configure them in the docs at: http://rexray.readthedocs.org/en/master/

If there is a storage platform you wish to see supported, we are always acceptance of PRs to be inclusive. 

If your question pertains to using REX-Ray with AWS but using Amazon Elastic Container Service, then that is something that is an untested configuration and architecture. REX-Ray must be installed, configured and running as a service on the host where the containers are located. 

If this answers your question, please close the issue.

**Comment by NetworkZIGI** [comment]
I means... 
If when I use Local Server(or VM), Can I use AWS EBS as REX-Ray volume driver?
I had not succeeded in connecting the AWS EBS as REX-Ray volume driver on the EC2 server.
I couldn't connected to AWS EBS as REX-Ray volume driver on the Local Server. 

=== Local Server Error ===
[root@localhost ~]# rexray volume list -l debug
DEBU[0000] updated log level  logLevel=debug
INFO[0000] [linux]
INFO[0000] [docker]
INFO[0000] ec2
DEBU[0000] core get drivers osDrivers=[linux] storageDrivers=[ec2] volumeDrivers=[docker]
INFO[0000] os driver initialized moduleName= provider=linux
DEBU[0000] error initializing driver driverName=ec2 error.provider=ec2
INFO[0000] docker volume driver initialized availabilityZone= iops=moduleName= provider=docker size= volumeRootPath=/data volumeType=
DEBU[0000] checking volume path cache setting pathCache=false
Oops, an error occured!

no storage drivers initialized

**Comment by clintonskitson** [comment]
@NetworkZIGI REX-Ray requires that the instance you are running REX-Ray from have access to the storage that you are requesting. In the case of AWS, you must be running RR from an EC2 instance. 

This is a limitation of the storage platforms. The bits and bytes from the the EBS volume get plumbed by AWS through your EC2 instance.
