### ISSUE TITLE
Virtualbox: storage controller not found

### ISSUE THREAD

**Issue by h0tbird** [emccode/rexray#392]
I am using the Virtualbox storage driver. I can create volumes but I can't attach volumes to my docker host. This is my current `REX-Ray` version:
```
core@node-1 ~ $ rexray version
DEBU[0000] updated log level                             logLevel=debug
Binary: /opt/bin/rexray
SemVer: 0.3.3
OsArch: Linux-x86_64
Branch: v0.3.3
Commit: b30fb870b5b94cd8368824460ad020bfcf20be3a
Formed: Thu, 21 Apr 2016 19:41:36 UTC
```
... and my config:
```
core@node-1 ~ $ cat /etc/rexray/config.yml
rexray:
  logLevel: debug
  storageDrivers:
  - virtualbox

virtualbox:
  endpoint: http://172.17.8.1:18083
  volumePath: /Users/marc.villacorta/VirtualBox Volumes
  controllerName: SATA
```

... and this is the error I get:
```
core@node-1 ~ $ rexray volume attach --volumeid bf12ea48-3138-4989-9cc6-2d438df539e6 --instanceid ee218f7d-42d6-4346-927a-9069167aeb58
DEBU[0000] updated log level                             logLevel=debug
INFO[0000] [linux]
INFO[0000] [docker]
INFO[0000] [virtualbox]
DEBU[0000] core get drivers                              osDrivers=[linux] storageDrivers=[virtualbox] volumeDrivers=[docker]
INFO[0000] storage driver initialized                    endpoint=http://172.17.8.1:18083 localMachineNameOrId= moduleName= password= provider=virtualbox tls=false userName= volumePath=/Users/marc.villacorta/VirtualBox Volumes
INFO[0000] docker volume driver initialized              availabilityZone= iops= moduleName= provider=docker size= volumeRootPath=/data volumeType=
INFO[0000] os driver initialized                         moduleName= provider=linux
DEBU[0000] checking volume path cache setting            pathCache=false
INFO[0000] sdm.AttachVolume                              driverName=virtualbox force=false instanceID=ee218f7d-42d6-4346-927a-9069167aeb58 moduleName= runAsync=false volumeID=bf12ea48-3138-4989-9cc6-2d438df539e6
FATA[0000] error attaching volume                        inner=storage controller not found moduleName= volumeID=bf12ea48-3138-4989-9cc6-2d438df539e6
```

I have a `SATA` controller (as documented) but my primary controller is `IDE`. I boot `CoreOS` from my IDE controller:

![screen shot 2016-04-27 at 15 23 16](https://cloud.githubusercontent.com/assets/417440/14853491/04eaa036-0c8c-11e6-8b9e-c97bd8474561.png)

Any idea? Thank you!

**Comment by h0tbird** [comment]
I have removed the `IDE` controller but I get the same error:
```
core@node-1 ~ $ rexray volume attach --volumeid 18fa1604-33fa-4a1f-9d17-67e682fbc68c
FATA[0000] error attaching volume                        inner=storage controller not found moduleName= volumeID=18fa1604-33fa-4a1f-9d17-67e682fbc68c
```

![screen shot 2016-04-27 at 15 55 28](https://cloud.githubusercontent.com/assets/417440/14854613/b50ebb92-0c90-11e6-8904-d0dbb71ddcb6.png)

**Comment by h0tbird** [comment]
Ah! Sorry, I am running VirtualBox `5.0.18` on OSX `10.11.3`

**Comment by clintonskitson** [comment]
There is a configuration option for VirtualBox to set your controller name.
In your case that option should say SATA. Can you try that?

**Comment by h0tbird** [comment]
As you can see in the screenshots the name is already `SATA`.
I have this line in my `Vagrantfile`:
```
vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata"]
```

**Comment by clintonskitson** [comment]
See the REX-Ray configuration.

http://rexray.readthedocs.org/en/stable/user-guide/storage-providers/#configuration_5

`  controllerName: name`

**Comment by h0tbird** [comment]
Thank you @clintonskitson I am aware of that, the documentation says:

> Hot-Plugging is required, which limits the usefulness of this driver to SATA only. Ensure that your VM has pre-created this controller and it is named SATA. Otherwise the controllerName field must be populated with the name of the controller you wish to use. The port count must be set manually as it cannot be increased when the VMs are on. A count of 30 is sugggested.

My `/etc/rexray/config.yml` configuration file already has `controllerName` defined although it is not really needed because I am using the default `SATA` name. Again, here you have my config:

```
core@node-1 ~ $ cat /etc/rexray/config.yml
rexray:
  logLevel: debug
  storageDrivers:
  - virtualbox

virtualbox:
  endpoint: http://172.17.8.1:18083
  volumePath: /Users/marc.villacorta/VirtualBox Volumes
  controllerName: SATA
```

**Comment by clintonskitson** [comment]
@h0tbird Is it possible that you have two vbox instances with the same MAC address? The lookup for the machine is occuring via the MAC address and this could cause it to not be able to find the proper vbox instance.

**Comment by h0tbird** [comment]
Yes I do, I was not aware of that:
```
core@master-1 ~ $ ip l show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 08:00:27:7a:3d:20 brd ff:ff:ff:ff:ff:ff
```

```
core@node-1 ~ $ ip l show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 08:00:27:7a:3d:20 brd ff:ff:ff:ff:ff:ff
```

I don't understand why Vagrant is doing that but I will modify my `Vagrantfile` to generate random MACs. I don't know how to do that... I will google for it...

**Comment by clintonskitson** [comment]
See here https://github.com/emccode/vagrant/blob/master/playa-mesos/Vagrantfile#L62

**Comment by h0tbird** [comment]
Awesome! That worked. One million thanks! Great 👍
