### ISSUE TITLE
Add libstorage commit ID to version

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#438]
Since libStorage is a critical part of the REX-Ray architecture it would be great to be able to identify which libStorage commit/version is being used as a part of REX-Ray. This could show up in the `rexray version` command to assist in troubleshooting.

**Comment by akutz** [comment]
Hi @clintonskitson,

This is a great idea. The info is already at `github.com/emccode/libstorage/api.Version`. I'll add it to RR when I fix the Makefile generation code.

**Comment by akutz** [comment]
Closed with #445.
