### ISSUE TITLE
Docker fails to re-create volume

### ISSUE THREAD

**Issue by pietervisser** [emccode/rexray#442]
Hi, I experience an issue with creating volumes using the docker CLI. When I remove a volume **and directly list the volumes**, re-creating the volume using docker does not work. re-creating the volume directly with rexray cli does work. The only way to 'resolve' this issue is rebooting the machine.

Create a volume
```
docker volume create --driver rexray --opt size=10 --name hello
docker volume ls

DRIVER              VOLUME NAME
rexray              hello
```

Remove the volume **and directly** list the volumes, the volume still is shown.
```
docker volume rm hello; docker volume ls
DRIVER              VOLUME NAME
rexray              hello
```
after a few seconds, check the volumes again, the volume got removed (also confirmed with rexray cli)
```
docker volume ls
DRIVER              VOLUME NAME
```

Now trying to re-create the volume does not work
```
docker volume create --driver rexray --opt size=10 --name hello
docker volume ls

DRIVER              VOLUME NAME
```

recreating the volume using rexray cli does work:
```
rexray volume create --volumename=hello --size=10
docker volume ls
DRIVER              VOLUME NAME
rexray              hello
```

Setup:
CoreOS alpha (1053.2.0)
REX-Ray: 0.3.3
Docker: 1.10.3
Storage Provider: GCE

**Comment by clintonskitson** [comment]
@pietervisser I was able to reproduce this as well using the GCE driver.

```
rexray:
  logLevel: debug
  storageDrivers:
    - gce
gce:
  keyfile: /root/gce.json
```

Turning on debug mode I found that Docker was not making the call to create the volume. I then updated to the latest release of Docker in CoreOS and this seemed to fix the problem you were seeing.

```
instance-5 docker # /opt/bin/docker volume create --driver rexray --opt size=10 --name hello
hello
instance-5 docker # /opt/bin/docker volume rm hello
hello
instance-5 docker # /opt/bin/docker volume ls
DRIVER              VOLUME NAME
rexray              instance-5
rexray              test
rexray              testing10
rexray              testing11
rexray              testing5
rexray              tt1
rexray              tt2
instance-5 docker # /opt/bin/docker volume create --driver rexray --opt size=10 --name hello
hello
instance-5 docker # /opt/bin/docker volume ls
DRIVER              VOLUME NAME
rexray              hello
rexray              instance-5
rexray              test
rexray              testing10
rexray              testing11
rexray              testing5
rexray              tt1
rexray              tt2
instance-5 docker # /opt/bin/docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
```

**Comment by pietervisser** [comment]
@clintonskitson thanks for checking this out. It looks like updating to Docker 1.11.2 resolves these issues!

**Comment by pacoxu** [comment]
Same issue in docker 1.13 + rexray 0.4. Try to upgrade rexray and test again.

**Comment by kacole2** [comment]
@pacoxu please make sure you are using the latest for your specified platform. v0.6.3 is currently the latest. In addition, Docker had added `docker volume rm --force <volumename>` in 1.13 to clear out any memory cache in the engine.
