### ISSUE TITLE
Weird issue with Docker

### ISSUE THREAD

**Issue by Arkan** [emccode/rexray#46]
Hi there,

I tried to configure Rex-ray(0.1 and 0.2) on a CoreOS(801) with Docker 1.8.1. 
And here is what I get. https://gist.github.com/Arkan/55ed62a965db1b9a4ee3
As you can see, the first time, when the volume doesn't exist, it is created, and then mounted correctly.
The second time, the volume exists, and there is an error with Docker(or REX-ray?)
Do you have any idea on what's going on here? 

Thanks

**Comment by clintonskitson** [comment]
Can you run the docker daemon in another window as well?  I am assuming
this has to do with the new Volume API recently introduced.  There is an
issue similar to this I believe.

**Comment by Arkan** [comment]
I've updated the gist with what you asked: https://gist.github.com/Arkan/55ed62a965db1b9a4ee3

Tell me if you need anything else.

**Comment by clintonskitson** [comment]
Could this possibly be a graph driver issue?  Have you tried running the same set of commands without a volume driver attachment?  `docker -dD` would get your more detail in your debug.

**Comment by Arkan** [comment]
Without a volume driver it works as expected.
With the debug mode, here is what I get:

```
core@ip-10-0-0-75 ~ $ docker -D run -ti -v test:/data --volume-driver=rexray busybox sh
DEBU[0007] [hijack] End of stdout
DEBU[0016] End of CmdRun(), Waiting for hijack to finish.
Error response from daemon: Cannot start container 58e436af5b32de6805bd0c2c1c3b4006cb41076ae77a36bfbe445c42f4a470db: Failed to initialize logging driver: open /var/lib/docker/containers/58e436af5b32de6805bd0c2c1c3b4006cb41076ae77a36bfbe445c42f4a470db/58e436af5b32de6805bd0c2c1c3b4006cb41076ae77a36bfbe445c42f4a470db-json.log: no such file or directory
core@ip-10-0-0-75 ~ $
```

**Comment by clintonskitson** [comment]
Can you send the AMI of the coreos image?

**Comment by Arkan** [comment]
It is a CoreOS 801 with docker 1.8.1.
You can take a look at the information showed by docker info.


Le sam. 12 sept. 2015 à 00:54, Clinton Kitson <notifications@github.com> a
écrit :

**Comment by Arkan** [comment]
Ami is ami-50f4b927, updated to the Alpha Channel(801) to have docker 1.8.1 installed.

**Comment by clintonskitson** [comment]
Having a problem replicating this.  I just spun up `ami-a36e94e7` from `North CA` and it matched versions of Docker etc.  I didn't experience any problems..  Can you try this image?

**Comment by Arkan** [comment]
Hey, 
So I tried with this ami, and it worked fine. 
The issue seems to be related with CoreOS+Docker+Mesos. 
I don't have any solution for the moment, but Rexray works fine :)

To sum up, 
* CoreOS 801 + Docker 1.8.1 + REX-ray = OK
* CoreOS 801 + Docker 1.8.1 + Mesos + REX-ray = Fail

I'll keep you posted on this thread.
Thanks for the help, and I'm closing this issue for the moment.
