### ISSUE TITLE
RR issue with libstorage

### ISSUE THREAD

**Issue by getstek** [emccode/rexray#470]
Hi,

I have installed RR on a CentOS7 node and am trying to connect back to a ScaleIO cluster. I get the following errors in the rexray.log file:

```
time="2016-06-22T07:32:22Z" level=error msg="default module(s) failed to initialize" error.configKey=libstorage.server.services error.obj=<nil> time=1466580742 
time="2016-06-22T07:32:22Z" level=error msg="error starting rex-ray" error.configKey=libstorage.server.services error.obj=<nil> time=1466580742
```

Similarly when I run "rexray volume -l debug" I get an error:

```
un 22 07:32:08 dc01-worker-01 systemd[1]: Started rexray.
Jun 22 07:32:08 dc01-worker-01 systemd[1]: Starting rexray...
[root@dc01-worker-01 ~]# rexray volume -l debug
DEBU[0000] updated log level                             logLevel=debug
DEBU[0000] os.args                                       time=1466580736 val=[rexray volume -l debug]
DEBU[0000] activating libStorage                         cmd=volume time=1466580736
DEBU[0000] libStorage auto service mode disabled; service name empty  time=1466580736
DEBU[0000] starting embedded libStorage server           time=1466580736
DEBU[0000] created scoped scope                          new=libstorage.server parentScopes=rexray,
INFO[0000] configured logging                            libstorage.logging.level=debug server=relic-stalker-il time=1466580736
INFO[0000] initializing server                           server=relic-stalker-il time=1466580736
INFO[0000] initializing default endpoint                 autoEndpointMode=unix server=relic-stalker-il time=1466580736
INFO[0000] initializing auto unix endpoint               endpoint=libstorage.server.endpoints.localhost server=relic-stalker-il time=1466580736
DEBU[0000] endpoint info                                 address=unix:///var/run/libstorage/454437278.sock endpoint=libstorage.server.endpoints.localhost server=relic-stalker-il time=1466580736
DEBU[0000] created scoped scope                          new=libstorage.server.endpoints.localhost parentScopes=libstorage.server,rexray,
INFO[0000] configured endpoint                           address=unix:///var/run/libstorage/454437278.sock endpoint=localhost server=relic-stalker-il time=1466580736
INFO[0000] server created                                server=relic-stalker-il time=1466580736
INFO[0000] initialized endpoints                         server=relic-stalker-il time=1466580736
INFO[0000] initializing server services                  server=relic-stalker-il time=1466580736
Oops, an error occured!

  invalid format

To correct the error please review:
```

ScaleIO is online and I can verify the API gateway is responding as required, finally the RR config file for ScaleIO shows:

```
rexray:
  logLevel: warn
  osDrivers:
  - linux
  storageDrivers:
  - scaleio
  volumeDrivers:
  - docker
  volume:
    mount:
      preempt: true
    unmount:
      ignoreusedcount: true
scaleio:
  endpoint: https://10.10.254.36/api
  insecure: true
  apiVersion: "2.0"
  useCerts: true
  userName: admin
  password: 'xxx'
  systemID: 0
  protectionDomainName: protection_domain01
  storagePoolName: containerPool
  thinOrThick: ThinProvisioned
```

**Comment by sebmoule** [comment]
I have the same issue on Ubuntu 16.04 and Openstack storage backend.
I download Rexray 0.3.3 and it works, it seams to have a problem with libstorage configuration.
Does rexray is still compatible with openstack with changes from 0.3.3 to 0.4 ?

also why we can't anymode download .deb package on repository : https://dl.bintray.com/emccode/rexray/stable/0.3.3/ ? there is only .tar.gz remains (so without service..)

thanks

**Comment by sebmoule** [comment]
Same problem here on Ubuntu 16.04 and openstack backend.

I'm not sur but it seams that rexray 0.4 with libstorage is no more (yet ?) compatible with openstack ?

**Comment by kacole2** [comment]
ping @cduchesne, can you assist with the ScaleIO portion since you've done the most testing?

@sebmoule you have a different issue. Please review the release notes and documentation for v0.4.0. At this time, only ScaleIO, Isilon, and VirtualBox are supported platforms for v0.4.0. The remaining platforms are targeted for v0.4.1 & v0.4.2 releases. https://github.com/emccode/rexray/releases/tag/v0.4.0 & http://rexray.readthedocs.io/en/latest/ . Please continue using v0.3.3 for OpenStack.

**Comment by kacole2** [comment]
@sebmoule v0.3.3 .deb file is being tracked in #468. Will be fixed soon

**Comment by akutz** [comment]
Hi @kacole2, you should be able to solve this one. Look at the provided config and then the documentation.

**Comment by akutz** [comment]
Hint - he's not using a 0.4.0 config.

**Comment by getstek** [comment]
Does the libstorage.server.libstorage.storage.driver key completely replace the rexray config?

I mean this:

```
rexray:
  logLevel: warn
  osDrivers:
  - linux
  storageDrivers:
  - scale
```

Would it become:

```
libstorage:
  server:
  libstorage:
  storage:
  -  scaleio
```

**Comment by akutz** [comment]
Close! I'm mobile, so it will take a min. Hang on

**Comment by akutz** [comment]
Using auto service mode you can just do this:

libstorage:
  service: scaleio

**Comment by akutz** [comment]
Note the above config isn't formatted due to mobile. The service property should be indented under libstorage.

**Comment by akutz** [comment]
Hi @getstek,

I'm on my laptop now. Okay, so let's transform the original configuration example:

```
rexray:
  logLevel: warn
libstorage:
  service: scaleio
  integration:
    volume:
      operations:
        mount:
          preempt: true
        unmount:
          ignoreusedcount: true
scaleio:
  endpoint: https://10.10.254.36/api
  insecure: true
  apiVersion: "2.0"
  useCerts: true
  userName: admin
  password: 'xxx'
  systemID: 0
  protectionDomainName: protection_domain01
  storagePoolName: containerPool
  thinOrThick: ThinProvisioned
```

**Comment by getstek** [comment]
Looks good, this seems to have done the trick - thanks. Is there any way this could make it back into the documentation? It's clearer now as you've given me an example, much clearer than the docs make it.
