### ISSUE TITLE
Hide specific configuration parameters from logging and return

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#50]
Since the new foundational enhancements with an admin API and logging, we now need think about hiding configuration parameters in JSON conversion and logging.  

Considering the default behavior is to expose TCP admin session, a simple call like `http://ip:7979/r/module/instances` is going to expose too much information.  I would assume that returning this kind of information upon instantiation may be appropriate, but that returning it after that point should not be possible.

```
[
  {
    "id": 1,
    "typeId": 1,
    "name": "AdminModule",
    "config": {
      "address": "tcp://:7979"
    },
    "description": "The REX-Ray admin module",
    "started": true
  },
  {
    "id": 2,
    "typeId": 2,
    "name": "DockerRemoteVolumeDriverModule",
    "config": {
      "address": "unix:///run/docker/plugins/rexray-remote.sock",
      "config": {
        "LogLevel": "info",
        "StorageDrivers": [
          "ec2"
        ],
        "VolumeDrivers": [
          "docker"
        ],
        "OsDrivers": [
          "linux"
        ],
        "MinVolSize": 0,
        "RemoteManagement": false,
        "DockerVolumeType": "",
        "DockerIops": 0,
        "DockerSize": 0,
        "DockerAvailabilityZone": "",
        "AwsAccessKey": "A",
        "AwsSecretKey": "jSv",
```

**Comment by akutz** [comment]
Hi @clintonskitson,

Do you have the link you sent me a few weeks back on Slack about HTTP over the UNIX socket implementation?

**Comment by clintonskitson** [comment]
David does a good job of receiving the tcp/unix sockets here.
https://github.com/calavera/dkvolume/blob/master/api.go

And this is the Docker client making the calls to that API.
https://github.com/docker/docker/blob/master/pkg/plugins/client.go

**Comment by clintonskitson** [comment]
If you're thinking that a fix is to leverage the unix socket and file permissions then I would agree with the approach.  Realistically those creds are stored in files and in the environment, so I don't see any extra security problems if the TCP isn't being exposed.

**Comment by akutz** [comment]
Hi @clintonskitson,

I'm thinking the fix is both approaches. That's in part why I invented Golf. Also, so I could say I created Golf :)

**Comment by clintonskitson** [comment]
Next think you're gonna make the *Internet* =)
