### ISSUE TITLE
have build names follow `uname` characteristics

### ISSUE THREAD

**Issue by kacole2** [emccode/rexray#51]
following along from https://github.com/docker/compose/releases/tag/1.4.0

```
curl -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
```

we should have rexray be similar.
```
curl -L https://github.com/emccode/rexray/releases/download/0.2.0-rc1/rexray-`uname -s`-`uname -m`.tar.gz > /tmp/rexray-`uname -s`-`uname -m`.tar.gz
```

this means we should get rid of the `v` from the leading address and follow standard `uname` returns.

**Comment by akutz** [comment]
Hi @kacole2,

0.2.0 RC1 which was [released five days ago](https://github.com/emccode/rexray/releases/tag/v0.2.0-rc1) abandoned the `v` prefix as you mentioned above two hours ago. 

![image](https://cloud.githubusercontent.com/assets/101085/9864582/a40cc6e0-5b10-11e5-92ad-3ebbac40a805.png)

However, our file names are likely to retain the version information for now. [Here's](https://bintray.com/akutz/generic/rexray/0.2.0-rc2%2B16/view#files) an example:

![image](https://cloud.githubusercontent.com/assets/101085/9864589/c542074e-5b10-11e5-9ebe-becbb2e6c822.png)

**Comment by kacole2** [comment]
I think we are looking at two different things. Under the GitHub releases the file specifically has a v in it. Your screenshot shows the v. 

Then there is the bintray stuff. I don't know what I'm supposed to be using.

**Comment by akutz** [comment]
@kacole2,

You specifically said `leading`, and the previous versions had a `v` as a prefix to the entire file name. As for the rest, please hold your horses as I'm answering your other, similar issue.

**Comment by akutz** [comment]
@kacole2,

FWIW, the `v` that you noticed in the 0.2.0-rc1 release will be going away as well.

**Comment by akutz** [comment]
Hi @kacole2,

In fact, if you look on Bintray you'll see it already has.

**Comment by clintonskitson** [comment]
Let's clarify this.  I am assuming this is what we are moving forwards towards?

Release tag version: 0.2.0-rc1
Release title: 0.2.0-rc1
Release filename: rexray-0.2.0-rc1-linux-x86_64.tar.gz

**Comment by akutz** [comment]
Hi @clintonskitson,

That is correct. Or more specifically, here's an example for the version I'm working on now:

```
[0]akutz@pax:rexray$ make version
SemVer: 0.2.0-rc2+19+dirty
Binary: darwin_amd64
Branch: bugfix/ci-fix
Commit: 45837a4f44975382927373ebce52d6660d653201
Formed: Mon, 14 Sep 2015 22:30:41 CDT
[0]akutz@pax:rexray$
```

And here's the tarball created for the `linux_amd64` version: `rexray-linux_amd64-0.2.0-rc2+19+dirty.tar.gz`.

Let's pretend I've committed the above change so the repo is no longer dirty:

```
[0]akutz@pax:rexray$ make version
SemVer: 0.2.0-rc2+19
Binary: darwin_amd64
Branch: bugfix/ci-fix
Commit: 45837a4f44975382927373ebce52d6660d653201
Formed: Mon, 14 Sep 2015 22:30:41 CDT
[0]akutz@pax:rexray$
```

Note that the version is lacking the `dirty` tag: `rexray-linux_amd64-0.2.0-rc2+19.tar.gz`.

Now if I tagged the commit as `v0.2.0-rc3` this would happen:

```
[0]akutz@pax:rexray$ make version
SemVer: 0.2.0-rc3
Binary: darwin_amd64
Branch: bugfix/ci-fix
Commit: 45837a4f44975382927373ebce52d6660d653201
Formed: Mon, 14 Sep 2015 22:30:41 CDT
[0]akutz@pax:rexray$
```

Note the build number is dropped from the end because there are no commits beyond the tag: `rexray-linux_amd64-0.2.0-rc3.tar.gz`.

**Comment by clintonskitson** [comment]
LGTM
