### ISSUE TITLE
Rexray 0.4.2, ScaleIO 2.0.0.1. docker volume create fails with "Error looking up volume plugin rexray"

### ISSUE THREAD

**Issue by rafajeng** [emccode/rexray#517]
Hi, gurus

I'm a ScaleIO user but new to Rexray. I set up ScaleIO 2.0.0.1, Rexray 0.4.2 and Docker 1.10.3 on CentOS 7.2. The "rexray -s scaleio volume create/attach" both work, but "docker volume create" fails with "Error looking up volume plugin rexray". Is this a compatibility issue between docker and rexray?

Please help. Thanks in advance. 

    #docker volume create --driver=rexray --name=testVol --opt=size=40
    Error response from daemon: create testVol: create testVol: Error looking up volume plugin rexray: Post http://%2Frun%2Fdocker%2Fplugins%2Frexray.sock/Plugin.Activate: dial unix /run/docker/plugins/rexray.sock: connect: connection refused

	# docker run --name rafa_container4 --volume-driver=rexray -ti -v volrr1:/volrr1 centos /bin/bash
	docker: Error response from daemon: create volrr1: create volrr1: Error looking up volume plugin rexray: Post http://%2Frun%2Fdocker%2Fplugins%2Frexray.sock/Plugin.Activate: dial unix /run/docker/plugins/rexray.sock: connect: connection refused.

	# rexray -s scaleio volume create --volumename=volrr2 --size=40
	availabilityZone: pd1
	name: volrr2
	size: 40
	id: 65b9f93300000001
	type: sp1

	# uname -a
	Linux leo 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

	#rexray version
	REX-Ray
	-------
	Binary: /usr/bin/rexray
	SemVer: 0.4.2
	OsArch: Linux-x86_64
	Branch: v0.4.2
	Commit: ccecc846c2fd84af3fcae554bf98cf40b1b78f91
	Formed: Wed, 13 Jul 2016 02:39:50 CST

	#docker version
	Client:
	 Version:         1.10.3
	 API version:     1.22
	 Package version: docker-common-1.10.3-46.el7.centos.10.x86_64
	 Go version:      go1.6.3
	 Git commit:      d381c64-unsupported
	 Built:           Thu Aug  4 13:21:17 2016
	 OS/Arch:         linux/amd64

	Server:
	 Version:         1.10.3
	 API version:     1.22
	 Package version: docker-common-1.10.3-46.el7.centos.10.x86_64
	 Go version:      go1.6.3
	 Git commit:      d381c64-unsupported
	 Built:           Thu Aug  4 13:21:17 2016
	 OS/Arch:         linux/amd64

	# cat /etc/rexray/config.yml
	rexray:
	  modules:
		default-docker:
		  type:     docker
		  host:     unix:///run/docker/plugins/scaleio.sock
		  spec:     /etc/docker/plugins/scaleio.spec
		  libstorage:
			service: scaleio
	libstorage:
	  server:
		services:
		  scaleio:
			driver: scaleio
	scaleio:
	  endpoint:             https://10.32.197.25/api
	  insecure:             true
	  userName:             admin
	  password:             ABcd1234
	  systemName:           sio-linux
	  protectionDomainName: pd1
	  storagePoolName:      sp1

**Comment by kacole2** [comment]
welcome to the fun! 

The docker issue should be fixed by upgrade docker to something 1.11+. We've successfully tested 1.12 and all is working with the latest release as well. That error is something we've seen with earlier versions.

Second your rexray `config.yml` is a bit overblown. Try using the beta [REX-Ray Configuration Generator](http://rexrayconfig.emccode.com/) and see if that gives you something less convoluted. However, if it's working, then by all means you can keep using that.

**Comment by cduchesne** [comment]
@rafajeng - one quick note. When you set the host to unix:///run/docker/plugins/scaleio.sock, you essentially changed rexray's volume-driver name to scaleio. If you run "docker volume ls" you should see the volumes you created, and the driver name should should scaleio instead of rexray. Try re-running your docker commands with "--volume-driver=scaleio".

**Comment by kacole2** [comment]
@rafajeng any update?

**Comment by rafajeng** [comment]
Many Thanks!
Both @kcole2 and @cduchesne 's methods worked. The REX-Ray Configuration Generator provides a working config.yml:

	libstorage:
	  service: scaleio
	scaleio:
	  insecure: true
	  thinOrThick: ThinProvisioned
	  endpoint: https://10.32.197.26/api
	  userName: admin
	  password: ABcd1234
	  systemName: sio-linux
	  protectionDomainName: pd1
	  storagePoolName: sp1
          
`docker run --name rafa10 --volume-driver rexray -ti -v volrr1:/volrr1 centos /bin/bash` now successfully creates a 16GB scaleio volume, formats it and mounts it. **But how to get a different volume size? How to change the default volume size?**

The config generator only supports one service at time. **If I have both Isilon and ScaleIO configured in config.yml, how should I differentiate them in `docker run --volume-driver=rexray` command?**

**Comment by kacole2** [comment]
@rafajeng there's a few options

**how to get a different volume size? How to change the default volume size?**
your best bet is to pre-create volumes. you can use the help menu to see all the available commands if the platform supports things like the `iops` flag
 
1. you can use the REX-Ray cli using something like 
  ```
rexray volume create --name volrr1 --size 75
  ```

2. you can use the Docker cli to pre-create:
  ```
docker volume create -d rexray --name volrr1 --opt=size=75
  ```

To change the default volume size, checkout out the very bottom under `libStorage Options` on the [REX-Ray Configuration Generator](http://rexrayconfig.emccode.com/). It will look like this:
```
libstorage:
  service: scaleio
  integration:
    volume:
      operations:
        create:
          default:
            size: 25
scaleio:
  insecure: true
  thinOrThick: ThinProvisioned
  endpoint: http://127.0.0.1:18083
  userName: admin
  password: abc123
  systemName: sysv
  protectionDomainName: corp
  storagePoolName: gold
```


**If I have both Isilon and ScaleIO configured in config.yml, how should I differentiate them in docker run --volume-driver=rexray command?**
At this time, the configuration generator only supports a single service. However, you CAN have both Isilon and ScaleIO in the same rexray configuration using modules. Take a look at [the module documentation](http://rexray.readthedocs.io/en/stable/user-guide/config/#example-with-modules) for creating the modules. You were on the right track with your original configuration using the named `sock` which is the equivalent of new volume driver name. This will allow you to do the following:
```
$ docker run -ti --volume-driver=scaleio -v test:/test busybox
$ docker run -ti --volume-driver=isilon -v test:/test busybox
```
The `test` volume would be isolated to that particular storage platform based on the `sock` name. Make sense?

**Comment by rafajeng** [comment]
Thanks, @kacole2. Both "rexray volume create" and "docker volume create" work. The default size in config.yml also work. Is there anyway to specify volume size in `"docker run --volume-driver rexray ti -v vol1:/vol1fs centos /bin/bash"`?

**Comment by kacole2** [comment]
No. Hence, the reason why I said to pre-create. That's the only way to specify the option of size.

**Comment by rafajeng** [comment]
Thanks to @kacole2 and @cduchesne for the awesome help!  :)
