### ISSUE TITLE
CLI does not show inspect as a volume command

### ISSUE THREAD

**Issue by vladimirvivien** [emccode/rexray#537]
The REX-Ray CLI supports command `rexray volume inspect`.  However, when attempting get additional help for inspect with `rexray volume inspect --help`, the CLI does not return help.  Further more, `inspect` is not listed as part of the overall volume command set.  The following should list inspect and the `--help` flag should provide verbiage help for inspect.

```
$> rexray volume --help
The volume manager

Usage:
  rexray volume [flags]
  rexray volume [command]

Available Commands:
  map         Print the volume mapping(s)
  get         Get one or more volumes
  create      Create a new volume
  remove      Remove a volume
  attach      Attach a volume
  detach      Detach a volume
  mount       Mount a volume
  unmount     Unmount a volume
  path        Print the volume path
```

**Comment by akutz** [comment]
Hi @vladimirvivien,

The REX-Ray CLI's `volume` command [does not](https://github.com/emccode/rexray/search?utf8=%E2%9C%93&q=inspect) in fact support `inspect` as a sub-command. The analogous sub-command would be `get`:

```
$ rexray volume get -?
Get one or more volumes

Usage: 
  rexray volume get [flags]

Aliases:
  get, ls, list

Flags:
  -f, --format="yml": The output format (yml, json)
      --volumeid="": volumeid
      --volumename="": volumename

Global Flags:
  -c, --config="": The path to a custom REX-Ray configuration file
  -?, --help[=false]: Help for get
  -h, --host="tcp://:7979": The REX-Ray host
  -l, --logLevel="warn": The log level (error, warn, info, debug)
  -v, --verbose[=false]: Print verbose help information
```

As you can see, `get` is also aliased as `ls` and `list`. Additionally, the `get` sub-command is the *default* sub-command used if only `rexray volume` were to be executed. Thus executing `rexray volume` is the same as executing `rexray volume get|ls|list`.

**Comment by vladimirvivien** [comment]
@akutz 
That's interesting, since `rexray volume inspect` actually returns information and the CLI did not complain about it being an invalid subcommand.  Maybe it's just defaulting to `rexray volume` when the subcommand is invalid.

**Comment by akutz** [comment]
Hi @vladimirvivien,

Your hypothesis must be correct as [`inspect` clearly isn't registered](https://github.com/emccode/rexray/search?utf8=%E2%9C%93&q=inspect).

```
$ rexray volume lll
Oops, an error occured!

  no OS drivers initialized

To correct the error please review:

  - Debug output by using the flag -l debug
  - The REX-ray website at https://github.com/emccode/rexray
  - The on↓ine he↓p be↓ow

Get one or more volumes

Usage: 
  rexray volume get [flags]

Aliases:
  get, ls, list

Flags:
  -f, --format="yml": The output format (yml, json)
      --volumeid="": volumeid
      --volumename="": volumename

Global Flags:
  -c, --config="": The path to a custom REX-Ray configuration file
  -h, --host="tcp://:7979": The REX-Ray host
  -l, --logLevel="warn": The log level (error, warn, info, debug)
  -v, --verbose[=false]: Print verbose help information
```

I think what is happening is that the way I hacked things to allow for a default sub-command no only supports **no value** and defaults to a given sub-command, but supports **no known value**.

I did not actually want to provide this functionality as it is not supported by the underlying CLI framework which we use. I was asked to provide it and so hacked it together. It's not perfect because, well, it's doing some crazy dumb stuff to work at all. See the following:

```
func (c *CLI) initVolumeCmds() {

	c.volumeCmd = &cobra.Command{
		Use:              "volume",
		Short:            "The volume manager",
		PersistentPreRun: c.preRunActivateLibStorage,
		Run: func(cmd *cobra.Command, args []string) {
			if isHelpFlags(cmd) {
				cmd.Usage()
			} else {
				c.volumeGetCmd.Run(c.volumeGetCmd, args)
			}
		},
```

If the `volume` command is executed, if there is no help flag present, it runs the `volumeGetCmd`. So yes, that works with what I hypothesised as the reason for why your use case behaves that way.

**Comment by vladimirvivien** [comment]
@akutz 
Awesome, thanks for the explanation.  So it's working as designed it sounds like.

**Comment by vladimirvivien** [comment]
@akutz I just happen to type inspect thinking it was a subcommand, but I think it's ok for now.
