### ISSUE TITLE
rexray can not connect scaleio-gateway

### ISSUE THREAD

**Issue by James-Dao** [emccode/rexray#544]
Hi,
when i use rexray to connect scaleio gateway , it shows errors. such as,  rexray version is 0.4.2, docker version is 1.12.1 

ERRO[0000] default module(s) failed to initialize        error.useCerts=false error.userName=admin error.password="******" error.provider=scaleIO error.endpoint="https://192.168.2.18/api" error.insecure=true time=1472563068816
ERRO[0000] error starting rex-ray                        error.insecure=true error.useCerts=false error.userName=admin error.password="******" error.provider=scaleIO error.endpoint="https://192.168.2.18/api" time=1472563068816

config is such as, 

libstorage:
  service: scaleio
  server:
    services:
      scaleio:
        driver: scaleio
        scaleio:
          endpoint: https://192.168.2.18/api
          apiVersion: "2.0"
          insecure: true
          useCerts: false
          userName: admin
          password:*****
          systemName:
          protectionDomainName: default
          storagePoolName: defaultSP
          thinOrThick: ThinProvisioned

i can ensure that all config item is right.

**Comment by James-Dao** [comment]
these steps are all ok.
1./opt/emc/scaleio/sdc/bin/drv_cfg --query_guid
2. curl --insecure --user admin:XScaleio123 https://gw_ip:443/api/login

**Comment by cduchesne** [comment]
I don't see the scaleio systemName. You can get it via:

```scli --query_cluster```

This should show the cluster name near the top.

**Comment by James-Dao** [comment]
Is it required? I can work well in others data center.

**Comment by James-Dao** [comment]
I have two gateways, one is installed on ubuntu14 and another is on centos7.  using the same config file , it will work well which point to gateway running on ubuntu, because there is a issue on ubuntu  about scaleio certification, so i want to try centos7.

**Comment by cduchesne** [comment]
The systemName needs to be populated for it to work. It is for rexray/libstorage's verification.

**Comment by James-Dao** [comment]
Ok. I will try it. Thanks

**Comment by James-Dao** [comment]
It still does not work. 

ubuntu gateway version : 2.0.5014.0
centos gateway version: 2.0.7120.0


rexray config for ubuntu gateway:
libstorage:
  service: scaleio
  server:
    services:
      scaleio:
        driver: scaleio
        scaleio:
          endpoint: https://192.168.2.6/api
          apiVersion: "2.0"
          insecure: true
          useCerts: false
          userName: admin
          password: *****
          systemName:
          systemID: 173c29b837c20144
          protectionDomainName: default
          storagePoolName: defaultSP
          thinOrThick: ThinProvisioned

root@ubuntu:/home/ubuntu# service rexray start
Starting REX-Ray...SUCCESS!

  The REX-Ray daemon is now running at PID 2735. To
  shutdown the daemon execute the following command:

    sudo /usr/bin/rexray stop

root@ubuntu:/home/ubuntu# rexray volume ls
- attachments:
  - instanceID:
      id: 7213c89700000000
      driver: scaleio
    volumeID: 32bd8abf00000000
  availabilityZone: default
  name: test_volume
  size: 8
  id: 32bd8abf00000000
  type: defaultSP


change rexray config for centos7:
libstorage:
  service: scaleio
  server:
    services:
      scaleio:
        driver: scaleio
        scaleio:
          endpoint: https://192.168.2.18/api
          apiVersion: "2.0"
          insecure: true
          useCerts: false
          userName: admin
          password: *****
          systemName:
          systemID: 173c29b837c20144
          protectionDomainName: default
          storagePoolName: defaultSP
          thinOrThick: ThinProvisioned

root@ubuntu:/home/ubuntu# rexray service start -l debug
DEBU[0000] updated log level                             logLevel=debug
DEBU[0000] os.args                                       time=1472610201558 val=[rexray service start -l debug]
DEBU[0000] invoking service start                        os.Args=[rexray service start -l debug] time=1472610201558
DEBU[0000] starting in background                        time=1472610201558
Starting REX-Ray...DEBU[0000] trying to start service                       client=/var/run/rexray/client.sock time=1472610201558
DEBU[0001] accepted connection                           time=1472610202244
DEBU[0001] received data                                 time=1472610202265
FAILED!
DEBU[0001] exiting with error code 1

root@ubuntu:/home/ubuntu# curl --insecure --user admin:***** https://192.168.2.18:443/api/login
"YWRtaW46MTQ3MjYzOTkwMjQxNDplNTgwMGEwMzQ3ZDUzMDZiZjJmNmUyMjAwZjk4MmE0OA"

root@ubuntu:/home/ubuntu# /opt/emc/scaleio/sdc/bin/drv_cfg --query_guid
42590EDC-6FBB-46FB-B4E9-FADC62D35C71

**Comment by cduchesne** [comment]
You still have a blank systemName variable there. 

Also, sometimes the debug messages are easier to diagnose by simply running

```rexray volume ls```

It will try to self-start in the process of running the volume command.

**Comment by James-Dao** [comment]
I have found the issue. I degrade gateway , it will work well. Thanks

**Comment by cduchesne** [comment]
Oh good. I'll close this - feel free to re-open if you have any related issues.

**Comment by rafajeng** [comment]
Hi, @cduchesne

The problem seems to be only with newly released GW 2.0.0.2. Could you look into it?
