### ISSUE TITLE
Error starting service on Ubuntu 14.0.4 with Docker 1.12.1

### ISSUE THREAD

**Issue by JimBugwadia** [emccode/rexray#549]
I am unable to run the service on Ubuntu 14.0.4 with Docker 1.12.1. Here are the environment details and logs.

-----------------------------------------------------
<pre>

ubuntu@ip-10-10-133-16:~$ sudo rexray version  
REX-Ray
-------
Binary: /usr/bin/rexray
SemVer: 0.4.2
OsArch: Linux-x86_64
Branch: v0.4.2
Commit: ccecc846c2fd84af3fcae554bf98cf40b1b78f91
Formed: Tue, 12 Jul 2016 18:39:50 UTC

libStorage
----------
SemVer: 0.1.5
OsArch: Linux-x86_64
Branch: v0.4.2
Commit: e4cdd05c6c3737df79098f69215e2031b5e5565c
Formed: Tue, 12 Jul 2016 18:38:18 UTC
ubuntu@ip-10-10-133-16:~$ sudo docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
ubuntu@ip-10-10-133-16:~$ sudo /usr/bin/rexray start -l debug
DEBU[0000] updated log level                             logLevel=debug
DEBU[0000] os.args                                       time=1473006785224 val=[/usr/bin/rexray start -l debug]
DEBU[0000] invoking service start                        os.Args=[/usr/bin/rexray start -l debug] time=1473006785224
DEBU[0000] starting in background                        time=1473006785224
Starting REX-Ray...DEBU[0000] trying to start service                       client=/var/run/rexray/client.sock time=1473006785224
DEBU[0000] accepted connection                           time=1473006785517
DEBU[0000] received data                                 time=1473006785523
FAILED!
DEBU[0000] exiting with error code 1
ubuntu@ip-10-10-133-16:~$

</pre>

-----------------------------------------------------

<pre>

REX-Ray
-------
Binary: /usr/bin/rexray
SemVer: 0.4.2
OsArch: Linux-x86_64
Branch: v0.4.2
Commit: ccecc846c2fd84af3fcae554bf98cf40b1b78f91
Formed: Tue, 12 Jul 2016 18:39:50 UTC

libStorage
----------
SemVer: 0.1.5
OsArch: Linux-x86_64
Branch: v0.4.2
Commit: e4cdd05c6c3737df79098f69215e2031b5e5565c
Formed: Tue, 12 Jul 2016 18:38:18 UTC

time="2016-09-04T16:33:05Z" level=debug msg="dialing rex-ray client" addr="/var/run/rexray/client.sock" time=1473006785517
time="2016-09-04T16:33:05Z" level=info msg="created pid file" pid=6116 time=1473006785517
time="2016-09-04T16:33:05Z" level=debug msg="libStorage auto service mode disabled; service name empty" time=1473006785518
time="2016-09-04T16:33:05Z" level=debug msg="starting embedded libStorage server" time=1473006785518
time="2016-09-04T16:33:05Z" level=debug msg="created scoped scope" new=libstorage.server parentScopes="rexray,"

################################################################################
################################################################################

time="2016-09-04T16:33:05Z" level=info msg="configured logging" libstorage.logging.level=debug server=dirt-koala-lc time=1473006785521
time="2016-09-04T16:33:05Z" level=info msg="initializing server" server=dirt-koala-lc time=1473006785521
time="2016-09-04T16:33:05Z" level=info msg="initializing default endpoint" autoEndpointMode=unix server=dirt-koala-lc time=1473006785522
time="2016-09-04T16:33:05Z" level=info msg="initializing auto unix endpoint" endpoint=libstorage.server.endpoints.localhost server=dirt-koala-lc time=1473006785522
time="2016-09-04T16:33:05Z" level=debug msg="endpoint info" address="unix:///var/run/libstorage/563552397.sock" endpoint=libstorage.server.endpoints.localhost server=dirt-koala-lc time=1473006785522
time="2016-09-04T16:33:05Z" level=debug msg="created scoped scope" new=libstorage.server.endpoints.localhost parentScopes="libstorage.server,rexray,"
time="2016-09-04T16:33:05Z" level=info msg="configured endpoint" address="unix:///var/run/libstorage/563552397.sock" endpoint=localhost server=dirt-koala-lc time=1473006785523
time="2016-09-04T16:33:05Z" level=info msg="server created" server=dirt-koala-lc time=1473006785523
time="2016-09-04T16:33:05Z" level=info msg="initialized endpoints" server=dirt-koala-lc time=1473006785523
time="2016-09-04T16:33:05Z" level=info msg="initializing server services" server=dirt-koala-lc time=1473006785523
time="2016-09-04T16:33:05Z" level=debug msg="configured result schema validation" enabled=false server=dirt-koala-lc time=1473006785523
time="2016-09-04T16:33:05Z" level=error msg="default module(s) failed to initialize" error.configKey=libstorage.server.services error.obj=<nil> time=1473006785523
time="2016-09-04T16:33:05Z" level=error msg="error starting rex-ray" error.configKey=libstorage.server.services error.obj=<nil> time=1473006785523

</pre>

**Comment by cduchesne** [comment]
What storage system are you using?

Can you provide output for the following commands (please sensor your passwords in config)?

```cat /etc/rexray/config.yml```
```rexray volume ls -l debug```

**Comment by JimBugwadia** [comment]
I am using AWS EC2:

<pre>
  export REXRAY_STORAGEDRIVERS=ec2
</pre>

I don't have a /etc/rexray/config.yml - is that something I need to setup?

<pre>
ubuntu@ip-10-10-133-16:~$ sudo cat /etc/rexray/config.yml
cat: /etc/rexray/config.yml: No such file or directory
</pre>

<pre>

ubuntu@ip-10-10-133-16:~$ sudo rexray volume ls -v -l debug
DEBU[0000] updated log level                             logLevel=debug
DEBU[0000] os.args                                       time=1473011877708 val=[rexray volume ls -v -l debug]
DEBU[0000] activating libStorage                         cmd=get time=1473011877708
DEBU[0000] libStorage auto service mode disabled; service name empty  time=1473011877709
DEBU[0000] starting embedded libStorage server           time=1473011877709
DEBU[0000] created scoped scope                          new=libstorage.server parentScopes=rexray,
INFO[0000] configured logging                            libstorage.logging.level=debug server=mud-heron-cx time=1473011877712
INFO[0000] initializing server                           server=mud-heron-cx time=1473011877712
INFO[0000] initializing default endpoint                 autoEndpointMode=unix server=mud-heron-cx time=1473011877713
INFO[0000] initializing auto unix endpoint               endpoint=libstorage.server.endpoints.localhost server=mud-heron-cx time=1473011877713
DEBU[0000] endpoint info                                 address=unix:///var/run/libstorage/397307537.sock endpoint=libstorage.server.endpoints.localhost server=mud-heron-cx time=1473011877713
DEBU[0000] created scoped scope                          new=libstorage.server.endpoints.localhost parentScopes=libstorage.server,rexray,
INFO[0000] configured endpoint                           address=unix:///var/run/libstorage/397307537.sock endpoint=localhost server=mud-heron-cx time=1473011877714
INFO[0000] server created                                server=mud-heron-cx time=1473011877714
INFO[0000] initialized endpoints                         server=mud-heron-cx time=1473011877714
INFO[0000] initializing server services                  server=mud-heron-cx time=1473011877714
DEBU[0000] configured result schema validation           enabled=false server=mud-heron-cx time=1473011877714
Oops, an error occured!

  invalid format

To correct the error please review:

  - Debug output by using the flag -l debug
  - The REX-ray website at https://github.com/emccode/rexray
  - The on↓ine he↓p be↓ow

Get one or more volumes

Usage:
  rexray volume get [flags]

Aliases:
  get, ls, list

Flags:
  -f, --format="yml": The output format (yml, json)
      --volumeid="": volumeid
      --volumename="": volumename

Global Flags:
  -c, --config="": The path to a custom REX-Ray configuration file
  -?, --help[=false]: Help for get
  -h, --host="": The libStorage host.
  -l, --logLevel="warn": The log level (error, warn, info, debug)
  -s, --service="": The libStorage service.
  -v, --verbose[=false]: Print verbose help information

Docker Flags
      --libstorageIntegrationVolumeOperationsCreateDefaultAvailabilityZone="":
      --libstorageIntegrationVolumeOperationsCreateDefaultFsType="ext4":
      --libstorageIntegrationVolumeOperationsCreateDefaultIOPS="":
      --libstorageIntegrationVolumeOperationsCreateDefaultSize="16":
      --libstorageIntegrationVolumeOperationsCreateDefaultType="":
      --libstorageIntegrationVolumeOperationsCreateImplicit[=true]:
      --libstorageIntegrationVolumeOperationsMountPath="/var/lib/libstorage/volumes":
      --libstorageIntegrationVolumeOperationsMountPreempt[=false]:
      --libstorageIntegrationVolumeOperationsMountRootPath="/data":

Isilon Flags
      --isilonDataSubnet="":
      --isilonEndpoint="":
      --isilonGroup="":
      --isilonInsecure[=false]:
      --isilonNfsHost="":
      --isilonPassword="":
      --isilonQuotas[=false]:
      --isilonSharedMounts[=false]:
      --isilonUserName="":
      --isilonVolumePath="":

Linux Flags
      --linuxVolumeFilemode=448:
      --linuxVolumeRootpath="/data":

Module Flags
      --rexrayModuleStartTimeout="10s":

ScaleIO Flags
      --scaleioEndpoint="":
      --scaleioInsecure[=false]:
      --scaleioPassword="":
      --scaleioProtectionDomainID="":
      --scaleioProtectionDomainName="":
      --scaleioStoragePoolID="":
      --scaleioStoragePoolName="":
      --scaleioSystemID="":
      --scaleioSystemName="":
      --scaleioThinOrThick="":
      --scaleioUseCerts[=false]:
      --scaleioUserID="":
      --scaleioUserName="":
      --scaleioVersion="":

VFS Flags
      --vfsRoot="/var/lib/libstorage/vfs":

VirtualBox Flags
      --virtualboxControllerName="SATA":
      --virtualboxDiskIDPath="/dev/disk/by-id":
      --virtualboxEndpoint="http://10.0.2.2:18083":
      --virtualboxLocalMachineNameOrId="":
      --virtualboxPassword="":
      --virtualboxScsiHostPath="/sys/class/scsi_host/":
      --virtualboxTls[=false]:
      --virtualboxUsername="":
      --virtualboxVolumePath="":

libStorage Flags
      --libstorageClientCacheInstanceID="30m":
      --libstorageClientType="integration":
      --libstorageDeviceAttachTimeout="30s":
      --libstorageDeviceScanType=0:
      --libstorageEmbedded[=false]:
      --libstorageExecutorDisableDownload[=false]:
      --libstorageExecutorPath="/var/lib/libstorage/lsx-linux":
      --libstorageHost="":
      --libstorageHttpDisableKeepAlive[=false]:
      --libstorageHttpReadTimeout=300:
      --libstorageHttpWriteTimeout=300:
      --libstorageIntegrationDriver="docker":
      --libstorageIntegrationVolumeOperationsCreateDisable[=false]:
      --libstorageIntegrationVolumeOperationsMountPreempt[=false]:
      --libstorageIntegrationVolumeOperationsPathCacheAsync[=true]:
      --libstorageIntegrationVolumeOperationsPathCacheEnabled[=true]:
      --libstorageIntegrationVolumeOperationsRemoveDisable[=false]:
      --libstorageIntegrationVolumeOperationsUnmountIgnoreusedcount[=false]:
      --libstorageLoggingHttpRequests[=false]:
      --libstorageLoggingHttpResponses[=false]:
      --libstorageLoggingLevel="warning":
      --libstorageLoggingStderr="": The file to which to log os.Stdout
      --libstorageLoggingStdout="": The file to which to log os.Stderr
      --libstorageOsDriver="linux":
      --libstorageServerAutoEndpointMode="unix":
      --libstorageServerTasksExeTimeout="1m":
      --libstorageServerTasksLogTimeout="0s":
      --libstorageService="":
      --libstorageStorageDriver="libstorage":


DEBU[0000] exiting with default error code 1, r=&{}
ubuntu@ip-10-10-133-16:~$

</pre>

Thanks for the help!

**Comment by cduchesne** [comment]
Currently, EC2 EBS is supported in REX-Ray 0.3.3 and the documentation can be found here:  http://rexray.readthedocs.io/en/v0.3.3/. Support for EBS should be available in the next month or so, and support for EFS should be available in the coming week.

In either case, you have to tell REX-Ray more about your environment to get it to work. This is done by via a config file or setting several environment variables. I recommend you start with the config file.

You can install REX-Ray 0.3.3 via the following command:
```
curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -s -- stable 0.3.3
```

If you already installed REX-Ray, you'll want to remove it with apt-get first.

Once installed, you can create a configuration file /etc/rexray/config.yml. My Amazon configuration file looks like the following and works with REX-Ray 0.3.3:
```
rexray:
  storageDrivers:
  - ec2
  volume:
    mount:
      preempt: true
aws:
    accessKey: my_access_key
    secretKey: my_access_secret
    region: my_aws_region
    rexrayTag: optional_tag_to_track
```

If you want to use environment variables, you could use the following:
```
REXRAY_STORAGEDRIVERS=ec2
AWS_ACCESSKEY=my_access_key
AWS_REGION=my_aws_region
AWS_SECRETKEY=my_access_secret
AWS_REXRAYTAG=<optional tag to set for tracking volumes>

REXRAY_VOLUME_MOUNT_PREEMPT=<true if you want volumes to be force attached>
```

**Comment by JimBugwadia** [comment]
Chris, thanks! That worked with the /etc/rexray/config.yml.

I also tried with the env vars, but got an error message indicating no storage driver was initialized.

Closing this issue.

**Comment by cduchesne** [comment]
Great, glad you got it working
