### ISSUE TITLE
where is rexray config generator ?

### ISSUE THREAD

**Issue by slawekgh** [emccode/rexray#553]
Hi all, 

Where is rexray config generator ? :-)))))) 

I had a link (a couple days ago it worked fine) but now there is DELL marketing chaos and a lot of widgets and pictures :-) 

It was always :
http://rexrayconfig.emccode.com

sl

**Comment by kacole2** [comment]
@slawekgh we just fixed this about 2 minutes ago :)

the new domain is [http://rexrayconfig.codedellemc.com/](http://rexrayconfig.codedellemc.com/)

We couldn't put in a forwarding rule
