### ISSUE TITLE
RexRay on Ubuntu 16.04 using virtualbox does not list or mount volumes (RESOLVED)

### ISSUE THREAD

**Issue by cantbewong** [emccode/rexray#575]
When using a Ubuntu 16.04 host, running virtualbox, and using RexRay inside a VM hosted by virtual box, RexRay is unable to list, mount or unmount virtualbox managed volumes.

an error like this will appear in the vboxwebsrv output
```
00:08:27.094975 SQW01       error, raising SOAP exception
00:08:27.094980 SQW01    API method name:            IVirtualBox::FindMachine
00:08:27.094983 SQW01    API return code:            0x80bb0001 (VBOX_E_OBJECT_NOT_FOUND)
00:08:27.095005 SQW01    COM error info result code: 0x80bb0001 (VBOX_E_OBJECT_NOT_FOUND)
00:08:27.095011 SQW01    COM error info text:        Could not find a registered machine named ''
```

rexray volume list fails to return any volumes.

# Resolution

On Ubuntu the vboxwebsrv web service has a couple limitations.

1. The service can only see and mount/unmount volumes with virtualbox VMs started by the same user account running the webservice. And if the webservice is run as root/sudo, it does NOT get access to all VMs
2. The service attempts to read the /etc/pam file by default. Permissions on this file vary by distro. On Ubuntu 16, non-root accounts are denied access

*vboxwebsrv must be run as the same user account that will be used to start virtualbox VMs*

## how I made it work

 good idea to capture webservice output in a log file in case you need it later
`sudo mkdir -p /var/log/vbox`
`sudo chmod 777 /var/log/vbox`

*The following should NOT be as root or sudo'd*
*instead it must be run as the same account that will start any VMs using RexRay managed mounts*

*start a VM*
`VBoxManage startvm "myvmname" --type headless`

*start virtual box management web service*
*Ubuntu restricts access to /etc/pam and virtualbox must be told to avoid it*
`export VBOX_PAM_ALLOW_INACTIVE=true`
`VBoxManage setproperty websrvauthlibrary null`
`vboxwebsrv -H 0.0.0.0 -v --logfile /var/log/vbox/vbox.log`

*From another terminal session*
*login, install and configure rexray, test rexray*

Using google I also discovered unverified anecdotal claims that running the webservice as root has issues, but once it was working using my personal account, I stopped experiments. Someone advised creating a "vbox" account for running both virtualbox, and the webservice, and starting VMs. Didn't do it myself because I got it working for my development use case, but passing it along in case somebody else has a broader goal. 

If using vagrant to deploy virtualbox VMs, you may need to deduce the account used to start VMs.

**Comment by cantbewong** [comment]
Closing - Resolution has been added to issue description. This was created for the benefit of those scanning issues to resolve observed problems.

**Comment by akutz** [comment]
Thanks @cantbewong. The VBoxWebSrv typically isn't run as root which is why this likely has not been encountered until now. I know that the user running the web service must have write access to the configured path where new disks are created, but from your testing it appears that one user cannot see another user's VMs' disks via the VBoxWebSrv API. All good to know, thanks.
