### ISSUE TITLE
Rexray Issue:-Automatic unlimitted volume created in AWS Instance during deploying Mongo 3.1 on mesosspher cluster

### ISSUE THREAD

**Issue by pratapnanda** [emccode/rexray#576]
Hello Team,
I am wondering to see the result when i used to deploy MongoDB in Mesosphere cluster in AWS.
I have manually created a EBS volume in AWS("ec2-awsdata") and the deploy Application with External Volumes(using docker) in mesosphere(below Yml file).  Rex-ray didn't find my existing volume "ec2-awsdata" and tried to create  multiple volume in AWS in a loop.Then I forcefully destroy the deployment and manually delete those volume.
I dont understand where is my mistake or has some bugs in rexray for MongoDB

_Below are my configuration:_
```
**core@ip-10-0-2-222 ~ $ rexray version**
	Binary: /opt/mesosphere/packages/rexray--5969104330e3381cadedff3daf6e94000283bf32/bin/rexray
	SemVer: 0.3.3-dcos+7
	OsArch: Linux-x86_64
	Branch: (detached
	Commit: 1816ee3868550e07b90f00f57bfd7f737235cd93
	Formed: Wed, 31 Aug 2016 04:25:48 UTC
**core@ip-10-0-2-222 ~ $ rexray volume get**
	- name: ec2-awsdata
	  volumeid: vol-7da82fc9
	  availabilityzone: us-west-2a
	  status: available
	  volumetype: gp2
	  iops: 100
	  size: "1"
	  networkname: ""
	  attachments: []
	- name: ""
	  volumeid: vol-110d5498
	  availabilityzone: us-west-2b
	  status: in-use
	  volumetype: standard
	  iops: 0
	  size: "8"
	  networkname: ""
	  attachments:
	  - volumeid: vol-110d5498
	    instanceid: i-5463b4c1
	    devicename: /dev/sda1
	    status: attached
**core@ip-10-0-2-222 ~ $ docker version**
	Client:
	 Version:      1.10.3
	 API version:  1.22
	 Go version:   go1.5.4
	 Git commit:   3cd164c
	 Built:
	 OS/Arch:      linux/amd64

	Server:
	 Version:      1.10.3
	 API version:  1.22
	 Go version:   go1.5.4
	 Git commit:   3cd164c
	 Built:
	 OS/Arch:      linux/amd64
**core@ip-10-0-7-183 /etc/rexray $ cat config.yml**
	rexray:
	  loglevel: info
	  modules:
	    default-admin:
	      host: tcp://127.0.0.1:61003
	  storageDrivers:
	  - ec2
	  volume:
	    unmount:
	      ignoreusedcount: true
	aws:
	  accessKey: xxxxx
	  secretKey: xxxxx
	  region: us-west-2
```

**YML files** 
```
{
  "id": "/test-mongo",
  "instances": 1,
  "cpus": 0.1,
  "mem": 256.0,
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "mongo:3.1",
      "network": "BRIDGE",
      "portMappings": [
                      {
                         "containerPort": 27017,
                          "hostPort": 0,
                          "servicePort": 53376,
                          "protocol": "tcp"
                      }
            ],
      "forcePullImage": true
    },
    "volumes": [
      {
        "containerPath": "/data/test-mongo-volume",
        "external": {
          "name": "ec2-awsdata",
          "provider": "dvdi",
          "options": { "dvdi/driver": "rexray" }
        },
        "mode": "RW"
      },
      {
        "hostPath": "var-log",
        "containerPath": "/var/log/mongodb",
        "mode": "RW"
      }
    ]
  },
  "upgradeStrategy": {
    "minimumHealthCapacity": 0,
    "maximumOverCapacity": 0
  }
}
```

**error logs:**
```
core@ip-10-0-2-224 /var/log/rexray $ ls
rexray.log
core@ip-10-0-2-224 /var/log/rexray $ tail -f rexray.log
time="2016-10-06T08:19:07Z" level=info msg="waiting for volume creation to complete" driverName=ec2 moduleName=default-docker resp.VolumeId=0xc8204ecfc8 runAsync=false snapshotID= volumeID=
time="2016-10-06T08:19:07Z" level=info msg=vdm.Path driverName=docker moduleName=default-docker volumeID= volumeName=ec2-awsdata
time="2016-10-06T08:19:08Z" level=info msg=vdm.Path driverName=docker moduleName=default-docker volumeID= volumeName=ec2-awsdata
time="2016-10-06T08:19:09Z" level=info msg=vdm.Path driverName=docker moduleName=default-docker volumeID= volumeName=ec2-awsdata
time="2016-10-06T08:19:09Z" level=info msg=vdm.Path driverName=docker moduleName=default-docker volumeID= volumeName=ec2-awsdata
time="2016-10-06T08:19:10Z" level=info msg=vdm.Path driverName=docker moduleName=default-docker volumeID= volumeName=ec2-awsdata
time="2016-10-06T08:19:10Z" level=info msg=vdm.Path driverName=docker moduleName=default-docker volumeID= volumeName=bbf22b930d5a44635a3c2bfa699f9f2f99b7bc48e64f20524c8c981985fb0126
time="2016-10-06T08:19:10Z" level=info msg="getting path to volume" driverName=docker moduleName=default-docker volumeID= volumeName=bbf22b930d5a44635a3c2bfa699f9f2f99b7bc48e64f20524c8c981985fb0126
time="2016-10-06T08:19:10Z" level=info msg=sdm.GetVolume driverName=ec2 moduleName=default-docker volumeID= volumeName=bbf22b930d5a44635a3c2bfa699f9f2f99b7bc48e64f20524c8c981985fb0126
time="2016-10-06T08:19:10Z" level=info msg=sdm.GetVolumeAttach driverName=ec2 instanceID=i-5773714f moduleName=default-docker volumeID=vol-22b13696
```

**When I deploying different application ,it works perfect** .Below YML file works perfect as per expectation and it attached to AWS EBS sucessfully
```
{
  "id": "/test-docker",
  "instances": 1,
  "cpus": 0.1,
  "mem": 32,
  "cmd": "/usr/bin/tail -f /dev/null",
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "alpine:3.1",
      "network": "HOST",
      "forcePullImage": true
    },
    "volumes": [
      {
        "containerPath": "/data/test-rexray-volume",
        "external": {
          "name": "ec2-awsdata",
          "provider": "dvdi",
          "options": { "dvdi/driver": "rexray" }
        },
        "mode": "RW"
      },
      {
        "hostPath": "var-log",
        "containerPath": "/var/log/myapp",
        "mode": "RW"
      }
    ]
  },
  "upgradeStrategy": {
    "minimumHealthCapacity": 0,
    "maximumOverCapacity": 0
  }
}
```
I dont understand where is my mistake or rexray has some issue in MongoDB

**Comment by pratapnanda** [comment]
Did anyone tried to deploy MongoDB using rexray?

**Comment by kacole2** [comment]
i updated your comment with proper formatting. 

I'm seeing `SemVer: 0.3.3-dcos+7`. where did you get this binary? 

Installation should be done:
```
curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -s -- stable 0.3.3
```

Please update Docker to 1.12.1

Here is a sample AWS Config:
```
rexray:
  logLevel: warn
  storageDrivers:
  - ec2
  volume:
    mount:
      preempt: true
aws:
  accessKey: mykey
  secretKey: secretkey
```

checkout this this [demo using postgres](https://github.com/codedellemc/demo/tree/master/demo-persistence-with-postgres-marathon-docker) as a sample for a properly formatted Marathon json.

**Comment by pratapnanda** [comment]
SemVer: 0.3.3-dcos+7 binary available automatically with Mesosphere 1.8.4 version .
I have directly deploy Postgress without docker update .it deployed successfully but when i changed the image to mongo3.1 ,the same issue occurred ..
i have changed AWS config as per your instruction but same issue occurred . 

Now I am tying to update docker 1.12.1 and will test the same

**Comment by pratapnanda** [comment]
Many Thanks for answer.it is now working after declare volume a spec in your marathon app

**Comment by pratapnanda** [comment]
"Volumes": { "/data/configdb": {}, "/data/db": {} },

**Comment by chaitup** [comment]
@pratapnanda I am also trying to do the same, Is that solved by adding "Volumes": { "/data/configdb": {}, "/data/db": {} }, in marathon app. Can I see your updated marathon app, thanks.

**Comment by chaitup** [comment]
@kacole2 can you please help me in this

**Comment by chaitup** [comment]
This is my marathon file and I see the below error after deploying.

docker: Error response from daemon: no such file or directory.
See 'docker run --help'.
W0228 16:47:58.937952 100104 logging.cpp:91] RAW: Received signal SIGTERM from process 2727 of user 0; exiting

{
  "id": "/test-mongo",
  "cpus": 0.5,
  "mem": 512,
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "mongo:3.1",
      "network": "BRIDGE",
      "portMappings": [
                      {
                         "containerPort": 27017,
                          "hostPort": 9216,
                          "servicePort": 53376,
                          "protocol": "tcp"
                      }
            ],
      "forcePullImage": true
    },
    "volumes": [
      {
        "containerPath": "/data/test-mongo-volume",
        "external": {
          "name": "mongo-data",
          "provider": "dvdi",
          "options": { "dvdi/driver": "rexray" }
        },
        "mode": "RW"
      }
    ]
  },
  "upgradeStrategy": {
    "minimumHealthCapacity": 0,
    "maximumOverCapacity": 0
  }
}

**Comment by clintonskitson** [comment]
@chaitup I would suggest turning on debug mode to be able to view the exact docker command that is being used. 

It seems like this is the command that should be launched based on what you specified.
`docker run -ti --volume-driver=rexray -v mongo-data:/data/test-mongo-volume mongo:3.1`
