### ISSUE TITLE
Should the curl install script point to install.sh on GitHub?

### ISSUE THREAD

**Issue by akutz** [emccode/rexray#71]
Hi @clintonskitson (et. al),

Currently both the `install` and `install.sh` scripts are hosted on Bintray. I'm thinking that the latter should actually only be hosted on GitHub with the former pointing to `https://raw.githubusercontent.com/emccode/rexray/master/install.sh` instead of `https://dl.bintray.com/emccode/rexray/install.sh`. The reason for this is so that we can more easily update the actual installer -- it will only take a commit. 

If you agree, I'd like to make this change **ASAP** as it will require replacing the static installer, resetting its download count. I want that to happen well before the release of 0.2.0.

**Comment by clintonskitson** [comment]
Agreed

**Comment by akutz** [comment]
Closed with commit f555136d0f1 and an update to `install` on Bintray.
