### ISSUE TITLE
Reinstall of RR on Ubuntu causes 'no such file' error

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#78]
Problem after uninstalling and reinstalling RR under Ubuntu.

```
root@ec2-54-219-167-85:/home/ubuntu# curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -
(Reading database ... 77285 files and directories currently installed.)
Preparing to unpack rexray-latest-x86_64.deb ...
/var/lib/dpkg/info/rexray.prerm: line 2: /usr/bin/rexray: No such file or directory
```

Removal of files by `rm /var/lib/dpkg/info/rex*` looks to fix the problem.

**Comment by akutz** [comment]
Hi @clintonskitson,

I am unable to reproduce the issue based on the above description. Please find the steps I used below:

## Install `REX-Ray`
```
[0]akutz@ubuntu:rexray$ curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -
Selecting previously unselected package rexray.
(Reading database ... 65583 files and directories currently installed.)
Preparing to unpack rexray-latest-x86_64.deb ...
Unpacking rexray (0.2.0+rc4-1) ...
Setting up rexray (0.2.0+rc4-1) ...

REX-Ray has been installed to /usr/bin/rexray

SemVer: 0.2.0-rc4
Binary: Linux-x86_64
Branch: v0.2.0-rc4
Commit: cc3eabe9e4d908def02168e0522db3c5e978d55d
Formed: Mon, 21 Sep 2015 10:17:02 CDT
```

## Install `REX-Ray` again
```
[0]akutz@ubuntu:rexray$ curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -
(Reading database ... 65587 files and directories currently installed.)
Preparing to unpack rexray-latest-x86_64.deb ...
Unpacking rexray (0.2.0+rc4-1) over (0.2.0+rc4-1) ...
Setting up rexray (0.2.0+rc4-1) ...

REX-Ray has been installed to /usr/bin/rexray

SemVer: 0.2.0-rc4
Binary: Linux-x86_64
Branch: v0.2.0-rc4
Commit: cc3eabe9e4d908def02168e0522db3c5e978d55d
Formed: Mon, 21 Sep 2015 10:17:02 CDT
```

## Uninstall `REX-Ray` with `dpkg`
```
[0]akutz@ubuntu:rexray$ sudo dpkg -r rexray
(Reading database ... 65587 files and directories currently installed.)
Removing rexray (0.2.0+rc4-1) ...
```

## Reinstall `REX-Ray` 
```
[0]akutz@ubuntu:rexray$ curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -
Selecting previously unselected package rexray.
(Reading database ... 65583 files and directories currently installed.)
Preparing to unpack rexray-latest-x86_64.deb ...
Unpacking rexray (0.2.0+rc4-1) ...
Setting up rexray (0.2.0+rc4-1) ...

REX-Ray has been installed to /usr/bin/rexray

SemVer: 0.2.0-rc4
Binary: Linux-x86_64
Branch: v0.2.0-rc4
Commit: cc3eabe9e4d908def02168e0522db3c5e978d55d
Formed: Mon, 21 Sep 2015 10:17:02 CDT
```

## Uninstall `REX-Ray` with `dpkg`
```
[0]akutz@ubuntu:rexray$ sudo dpkg -r rexray
(Reading database ... 65587 files and directories currently installed.)
Removing rexray (0.2.0+rc4-1) ...
```

## Try to uninstall `REX-Ray` with `dpkg` again
```
[0]akutz@ubuntu:rexray$ sudo dpkg -r rexray
dpkg: warning: ignoring request to remove rexray which isn't installed
```

As you can see it works for me on Ubuntu 14.04. Also note that I installed `REX-Ray` multiple times and one uninstall is all that's required -- the second uninstallation after the first one fails.

**Comment by clintonskitson** [comment]
@akutz Try this order..

```
root@ec2-54-219-167-85:/home/ubuntu# rexray uninstall
REX-Ray is already stopped
 Removing any system startup links for /etc/init.d/rexray ...
   /etc/rc0.d/K20rexray
   /etc/rc1.d/K20rexray
   /etc/rc2.d/S20rexray
   /etc/rc3.d/S20rexray
   /etc/rc4.d/S20rexray
   /etc/rc5.d/S20rexray
   /etc/rc6.d/K20rexray
root@ec2-54-219-167-85:/home/ubuntu# curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -
(Reading database ... 77285 files and directories currently installed.)
Preparing to unpack rexray-latest-x86_64.deb ...
/var/lib/dpkg/info/rexray.prerm: line 2: /usr/bin/rexray: No such file or directory
dpkg: warning: subprocess old pre-removal script returned error exit status 127
dpkg: trying script from the new package instead ...
/var/lib/dpkg/tmp.ci/prerm: line 2: /usr/bin/rexray: No such file or directory
dpkg: error processing archive rexray-latest-x86_64.deb (--install):
 subprocess new pre-removal script returned error exit status 127
/var/lib/dpkg/info/rexray.postinst: line 2: /usr/bin/rexray: No such file or directory
dpkg: error while cleaning up:
 subprocess installed post-installation script returned error exit status 127
Errors were encountered while processing:

```

**Comment by akutz** [comment]
Hi @clintonskitson,

That's not an order so much as breaking the package system. Of course that fails. You basically removed a managed binary. If you want the install scripts to forgo RPMs and DEBs and use tarballs exclusively we can do that, but what you did is remove a managed component and then wonder why the manager complained...

**Comment by clintonskitson** [comment]
So what is the proposed set of commands to remove RR and then re add it at a later time?  How about an upgrade?

**Comment by clintonskitson** [comment]
I wonder if the uninstall portion shouldn't exist unless we are going to
engage the package management system to do so?

**Comment by akutz** [comment]
Hi @clintonskitson,

That depends, doesn't it? If you use the package manager you have to use the package manager. If you don't, you can use the `install` or `uninstall` commands. Upgrades work fine using the prescribed method that you choose to use. I was never in favor of packages, but people wanted them. And the fact is that if you use them, you don't have the luxury of removing the files later how you feel like removing them without understanding what's actually happening. That's why `dpkg` complained. It said it expected to find a managed file at `/usr/bin/rexray` to perform the uninstallation and it wasn't there as you already removed it. 

The process works fine, you just have to pick a process. Upgrades will work fine too as the packages will simply upgrade themselves. In the future, if you install it on a RPM or DEB system via the curl script know that you have to remove it via the package tool if you installed it via the package (or via the curl script as it uses packages for RPM 386/x64 systems and Deb x64 systems). 

It's not a real problem. It's more of an issue of doing an `rm -fr /` and wondering why the system didn't boot...

**Comment by akutz** [comment]
Hi @clintonskitson,

Yes, it *should* exist. You engaged the package system to do the install so you have to engage it to do the uninstall. Download the tarball and do the `install` manually and then do the `uninstall`. That works fine. 

Again, you engaged two different processes and are reflecting on why they broke each other. That's not the same thing as a thing being broken.

**Comment by akutz** [comment]
Hi @clintonskitson,

By the way, note that the `install` and `uninstall` commands are hidden from the help screen. They're not advertised except for people who would come to the documentation asking how to get REX-Ray working. And the fact is that except for Linux users, no one will be doing an installation anyway, so it's fine.

**Comment by clintonskitson** [comment]
Ok I'm good with that then.  I was thinking those were advertised commands.

**Comment by akutz** [comment]
Nah. I mean, for docs they will be, but the `install` script uses the RPM and DEB when the system supports it and only the `install` command from the tarball if no other option exists.

**Comment by akutz** [comment]
Hmm. Come to think of it. I *could* add detection in the uninstall command so that if it's invoked on a system where the package is installed it engages the appropriate package tool to perform the uninstallation.

**Comment by clintonskitson** [comment]
Yah was thinking the same thing, but not a top priority.
