### ISSUE TITLE
Add version information to rexray.log

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#83]
When RR starts, it would be nice to add the version information in the log file.

**Comment by akutz** [comment]
Something like this?

![image](https://cloud.githubusercontent.com/assets/101085/10146450/8f8b47e4-65ee-11e5-86e5-196eecacd4dd.png)

**Comment by clintonskitson** [comment]
Perfect

**Comment by akutz** [comment]
Closed with PR #90.
