### ISSUE TITLE
Add vendoring of depenendent packages for specific commits at releases

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#92]
It would be nice to add the ability to lock RR releases for dependent packages and tie the `glide.yaml` file to specific commits, preferably tied to other supported releases.

**Comment by akutz** [comment]
Hi @clintonskitson,

This will not be automated as it involves checking code back into the system as part of an automated build process. However, it's easy to accomplish by doing `glide guess` to get all of the project's dependencies. Place those in `glide.yaml` and then do a `glide up` to download them. Finally `glide pin` produces the `glide.yaml` output that contains all current reference IDs so you can lock things down.

This is handled for the 0.2.0 release in commit 9012ae3bbc5311.
