### ISSUE TITLE
Add a flag to make process to remove existing packages in /vendor directory

### ISSUE THREAD

**Issue by clintonskitson** [emccode/rexray#98]
When dependent packages get updated, a build can hit an error unless you manually clear out the vendor directory of existing packages.  I propose that we defaultly remove the packages, and have a flag that disables this functionality to ensure a build can happen quickly if desired.

**Comment by akutz** [comment]
Hi @clintonskitson,

Does PR #99 work for you?

**Comment by akutz** [comment]
Hi @clintonskitson,

By the way, I did not make the clean build the default as it's the antithesis to all other build systems be they other Makefile-driven projects, Visual Studio projects, Java projects, etc.

**Comment by clintonskitson** [comment]
@akutz LGTM

**Comment by clintonskitson** [comment]
`make clean build-linux-amd64`

**Comment by akutz** [comment]
Hi @clintonskitson,

I believe you'll like it better now that it has the following, additional targets:

* clean
* clean-all
* rebuild
* rebuild-all
* reinstall
* reinstall-all
* retest
* retest-all
* rebuild-linux-386
* rebuild-all-linux-386
* rebuild-linux-amd64
* rebuild-all-linux-amd64
* rebuild-darwin-amd64
* rebuild-all-darwin-amd64
